// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Schema-verified: each canonical name was matched against
// NattKh/CrimsonDesertModdingTools `pabgb_complete_schema.json`
// (canonical PA identifiers extracted from Korean error strings
// in CrimsonDesert.exe). Only fields whose mechanical snake→camel
// translation matched a known canonical name were shipped.
//
// v3 (snake_case) is the default emit; v3.1 emits the canonical `_camelCase`
// form. Round-trips identically — both names accepted on input.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("level_name", "_levelName"),
    ("map_icon_texture_info", "_mapIconTextureInfo"),
    ("discover_near_fog", "_discoverNearFog"),
    ("fog_map_icon_texture_info", "_fogMapIconTextureInfo"),
    ("fog_distance", "_fogDistance"),
    ("over_abyss_icon_texture_info", "_overAbyssIconTextureInfo"),
    ("over_abyss_fog_map_icon_texture_info", "_overAbyssFogMapIconTextureInfo"),
    ("over_abyss_fog_distance", "_overAbyssFogDistance"),
    ("discover_distance", "_discoverDistance"),
    ("show_icon_condition_type", "_showIconConditionType"),
    ("use_teleport", "_useTeleport"),
    ("use_guide_effect", "_useGuideEffect"),
    ("is_sub_inner_gimmick", "_isSubInnerGimmick"),
    ("check_game_level_load_state", "_checkGameLevelLoadState"),
    ("guide_effect_socket_name", "_guideEffectSocketName"),
    ("ore_vein_index", "_oreVeinIndex"),
    ("discover_type", "_discoverType"),
    ("ignore_same_gimmick_discover_distance", "_ignoreSameGimmickDiscoverDistance"),
    ("discover_gimmick_state_hash", "_discoverGimmickStateHash"),
];
