// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Each entry maps the Rust struct field name (snake_case, what shape='v3'
// emits today) to the canonical Pearl Abyss C++ identifier (with leading
// underscore, what shape='v3.1' emits). Mechanical transliteration:
// snake_case → prepend `_` + lowerCamelCase. v3 names are NEVER overwritten;
// these aliases just enable v3.1 consumers (DMM v2.0.0-beta etc.) to request
// the canonical names.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("level_name", "_levelName"),
    ("data_list", "_dataList"),
    ("map_icon_texture_info", "_mapIconTextureInfo"),
    ("discover_near_fog", "_discoverNearFog"),
    ("fog_map_icon_texture_info", "_fogMapIconTextureInfo"),
    ("fog_distance", "_fogDistance"),
    ("over_abyss_icon_texture_info", "_overAbyssIconTextureInfo"),
    ("over_abyss_fog_map_icon_texture_info", "_overAbyssFogMapIconTextureInfo"),
    ("over_abyss_fog_distance", "_overAbyssFogDistance"),
    ("discover_distance", "_discoverDistance"),
    ("show_icon_condition_type", "_showIconConditionType"),
    ("use_teleport", "_useTeleport"),
    ("use_guide_effect", "_useGuideEffect"),
    ("is_sub_inner_gimmick", "_isSubInnerGimmick"),
    ("check_game_level_load_state", "_checkGameLevelLoadState"),
    ("unk_new_u8_a", "_unkNewU8A"),
    ("unk_new_u8_b", "_unkNewU8B"),
    ("completed_discover_map_icon_texture_info", "_completedDiscoverMapIconTextureInfo"),
    ("over_abyss_completed_discover_map_icon_texture_info", "_overAbyssCompletedDiscoverMapIconTextureInfo"),
    ("guide_effect_socket_name", "_guideEffectSocketName"),
    ("ore_vein_index", "_oreVeinIndex"),
    ("discover_type", "_discoverType"),
    ("ignore_same_gimmick_discover_distance", "_ignoreSameGimmickDiscoverDistance"),
    ("discover_gimmick_state_hash", "_discoverGimmickStateHash"),
];
