// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Each entry maps the Rust struct field name (snake_case, what shape='v3'
// emits today) to the canonical Pearl Abyss C++ identifier (with leading
// underscore, what shape='v3.1' emits). Mechanical transliteration:
// snake_case → prepend `_` + lowerCamelCase. v3 names are NEVER overwritten;
// these aliases just enable v3.1 consumers (DMM v2.0.0-beta etc.) to request
// the canonical names.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("byte_at_16", "_byteAt16"),
    ("lookup_u32_a", "_lookupU32A"),
    ("lookup_u32_b", "_lookupU32B"),
    ("unk_u32_b", "_unkU32B"),
    ("byte_at_28", "_byteAt28"),
    ("byte_at_29", "_byteAt29"),
    ("byte_at_30", "_byteAt30"),
    ("byte_at_31", "_byteAt31"),
    ("lookup_u32_c", "_lookupU32C"),
    ("bounds", "_bounds"),
    ("size_pair", "_sizePair"),
    ("height_pair", "_heightPair"),
    ("unk_u32_d", "_unkU32D"),
    ("unk_u32_e", "_unkU32E"),
    ("unk_u32_f", "_unkU32F"),
    ("unk_f32_g", "_unkF32G"),
    ("lookup_u16_a", "_lookupU16A"),
    ("byte_at_82", "_byteAt82"),
    ("byte_at_83", "_byteAt83"),
    ("byte_at_84", "_byteAt84"),
    ("composite", "_composite"),
    ("lookup_u32_d", "_lookupU32D"),
    ("lookup_u32_e", "_lookupU32E"),
    ("lookup_u32_f", "_lookupU32F"),
    ("byte_at_126", "_byteAt126"),
];
