// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Schema-verified: each canonical name was matched against
// NattKh/CrimsonDesertModdingTools `pabgb_complete_schema.json`
// (canonical PA identifiers extracted from Korean error strings
// in CrimsonDesert.exe). Only fields whose mechanical snake→camel
// translation matched a known canonical name were shipped.
//
// v3 (snake_case) is the default emit; v3.1 emits the canonical `_camelCase`
// form. Round-trips identically — both names accepted on input.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("byte_at_16", "_isBlocked"),
    ("lookup_u32_a", "_levelName"),
    ("lookup_u32_b", "_sceneLevelPath"),
    ("unk_u32_b", "_maxPlayerCount"),
    ("byte_at_28", "_readOnly"),
    ("byte_at_29", "_addFieldStyle"),
    ("byte_at_30", "_fieldRegistType"),
    ("byte_at_31", "_crimeRegionBitmapPositionInfo"),
    ("lookup_u32_c", "_spawnPath"),
    ("bounds", "_returnPosition"),
    ("size_pair", "_boundaryPositionMin"),
    ("height_pair", "_boundaryPositionMax"),
    ("lookup_u16_a", "_detectInfo"),
    ("byte_at_82", "_natureRegionBitmapPositionInfo"),
    ("byte_at_83", "_alwaysCallVehicle_dev"),
    ("byte_at_84", "_startSectorIndex"),
];
