// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Each entry maps the Rust struct field name (snake_case, what shape='v3'
// emits today) to the canonical Pearl Abyss C++ identifier (with leading
// underscore, what shape='v3.1' emits). Mechanical transliteration:
// snake_case → prepend `_` + lowerCamelCase. v3 names are NEVER overwritten;
// these aliases just enable v3.1 consumers (DMM v2.0.0-beta etc.) to request
// the canonical names.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("mission_info", "_missionInfo"),
    ("platform_achievement_ids", "_platformAchievementIds"),
    ("type_", "_type"),
    ("questkey", "_questkey"),
    ("quest_group_key", "_questGroupKey"),
    ("quest_group_platform_id", "_questGroupPlatformId"),
    ("quest_link_info_list", "_questLinkInfoList"),
];
