// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// No v3.1 canonical aliases for this table (no schema match or no fields
// match the canonical name set). v3 (snake_case) and v3.1 emit identically.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[];
