// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Schema-verified: each canonical name was matched against
// NattKh/CrimsonDesertModdingTools `pabgb_complete_schema.json`
// (canonical PA identifiers extracted from Korean error strings
// in CrimsonDesert.exe). Only fields whose mechanical snake→camel
// translation matched a known canonical name were shipped.
//
// v3 (snake_case) is the default emit; v3.1 emits the canonical `_camelCase`
// form. Round-trips identically — both names accepted on input.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("display_region_name", "_displayRegionName"),
    ("knowledge_info", "_knowledgeInfo"),
    ("parent_region_info", "_parentRegionInfo"),
    ("child_region_info_list", "_childRegionInfoList"),
    ("bitmap_color", "_bitmapColor"),
    ("region_type", "_regionType"),
    ("fog_clear_condition", "_fogClearCondition"),
    ("limit_vehicle_run", "_limitVehicleRun"),
    ("is_town", "_isTown"),
    ("is_wild", "_isWild"),
    ("is_none_play_zone", "_isNonePlayZone"),
    ("vehicle_mercenary_allow_type", "_vehicleMercenaryAllowType"),
    ("is_world_map_road_path_findable", "_isWorldMapRoadPathFindable"),
    ("gimmick_alias_pointer_list", "_gimmickAliasPointerList"),
    ("domain_faction_list", "_domainFactionList"),
    ("tag_list", "_tagList"),
];
