// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Each entry maps the Rust struct field name (snake_case, what shape='v3'
// emits today) to the canonical Pearl Abyss C++ identifier (with leading
// underscore, what shape='v3.1' emits). Mechanical transliteration:
// snake_case → prepend `_` + lowerCamelCase. v3 names are NEVER overwritten;
// these aliases just enable v3.1 consumers (DMM v2.0.0-beta etc.) to request
// the canonical names.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("display_region_name", "_displayRegionName"),
    ("knowledge_info", "_knowledgeInfo"),
    ("region_enter_knowledge_info_list", "_regionEnterKnowledgeInfoList"),
    ("parent_region_info", "_parentRegionInfo"),
    ("child_region_info_list", "_childRegionInfoList"),
    ("bitmap_color", "_bitmapColor"),
    ("overrided_max_height", "_overridedMaxHeight"),
    ("region_type", "_regionType"),
    ("fog_clear_condition", "_fogClearCondition"),
    ("limit_vehicle_run", "_limitVehicleRun"),
    ("is_town", "_isTown"),
    ("is_wild", "_isWild"),
    ("is_ui_map_disable", "_isUiMapDisable"),
    ("is_housing_region", "_isHousingRegion"),
    ("is_none_play_zone", "_isNonePlayZone"),
    ("vehicle_mercenary_allow_type", "_vehicleMercenaryAllowType"),
    ("is_world_map_road_path_findable", "_isWorldMapRoadPathFindable"),
    ("u8_123", "_u8123"),
    ("gimmick_alias_pointer_list", "_gimmickAliasPointerList"),
    ("domain_faction_list", "_domainFactionList"),
    ("tag_list", "_tagList"),
];
