// Auto-generated by scripts/generate_v3_1_aliases.py — hand-edited 2026-05-12
// to add Mac-canonical aliases verified via IDA decompile of
// `sub_101893AF0` in CrimsonDesert_Steam (Mac binary).
//
// Schema-verified: each canonical name was matched against the Korean
// error strings in CrimsonDesert_Steam at 0x1073bc487..0x1073bcbd0
// (parser sub_101893AF0).
//
// v3 (snake_case) is the default emit; v3.1 emits the canonical `_camelCase`
// form. Round-trips identically — both names accepted on input.
//
// WIRE-LAYOUT NOTE (2026-05-12): Mac canonical has 27 wire fields; this
// Rust struct has 24. Some Rust placeholder fields appear to pack
// multiple Mac u8 fields into a single wider field (e.g.
// `combat_targeting_flags: u32` may represent Mac positions 8-11 packed,
// and `packed_flags_106: u8` represents the 1.06-added byte cluster).
// Per the existing fixture's roundtrip success, the wire byte count
// matches — but the field-by-field semantic mapping for placeholders
// is uncertain. Aliases below are only set where the Mac-canonical
// mapping is unambiguous.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("default_limit_summon_count", "_defaultLimitSummonCount"),
    ("default_limit_hire_count", "_defaultLimitHireCount"),
    ("max_limit_hire_count", "_maxLimitHireCount"),
    // NOTE: `far_from_leader_option` placeholder may actually represent Mac
    // canonical `_mercenaryType` (wire position 7). Alias retained as
    // `_farFromLeaderOption` (existing) pending 1.06 fixture verification.
    ("far_from_leader_option", "_farFromLeaderOption"),
    // `combat_targeting_flags: u32` — likely packs Mac positions 8-11
    // (_farFromLeaderOption + _isControllable + _isPlayable + _summonAfterRegist).
    // Not aliased pending verification.
    ("is_controllable", "_isControllable"),
    ("is_playable", "_isPlayable"),
    // CORRECTED: was "_setNewMercenaryIsMain" (a placeholder name that does
    // not exist in Mac canonical). Mac canonical at this wire position is
    // `_summonAfterRegist`.
    ("set_new_mercenary_is_main", "_summonAfterRegist"),
    ("main_mercenary_per_tribe", "_mainMercenaryPerTribe"),
    ("is_force_stackable", "_isForceStackable"),
    ("is_sellable", "_isSellable"),
    ("use_camp_level", "_useCampLevel"),
    ("apply_equip_item_stat", "_applyEquipItemStat"),
    ("spawn_position_type", "_spawnPositionType"),
    ("mercenary_type", "_mercenaryType"),
    ("is_growable", "_isGrowable"),
    ("parent_mercenary_group_info", "_parentMercenaryGroupInfo"),
    ("summon_owner_option", "_summonOwnerOption"),
    // `packed_flags_106` — 1.06-added byte; covers some subset of Mac
    // _checkItemNoOnPushToItem / _allowExceedLimitHireCount /
    // _isSelectMercenarySpawn / _unspawnOnFocusActorChanged /
    // _isMainDischargeable as packed bits. Not aliased (1:N mapping).
    ("shared_summon_count_tag", "_sharedSummonCountTag"),
    ("hired_skill_info_list", "_hiredSkillInfoList"),
];
