// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Schema-verified: each canonical name was matched against
// NattKh/CrimsonDesertModdingTools `pabgb_complete_schema.json`
// (canonical PA identifiers extracted from Korean error strings
// in CrimsonDesert.exe). Only fields whose mechanical snake→camel
// translation matched a known canonical name were shipped.
//
// v3 (snake_case) is the default emit; v3.1 emits the canonical `_camelCase`
// form. Round-trips identically — both names accepted on input.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("default_limit_summon_count", "_defaultLimitSummonCount"),
    ("default_limit_hire_count", "_defaultLimitHireCount"),
    ("max_limit_hire_count", "_maxLimitHireCount"),
    ("far_from_leader_option", "_farFromLeaderOption"),
    ("is_controllable", "_isControllable"),
    ("set_new_mercenary_is_main", "_setNewMercenaryIsMain"),
    ("main_mercenary_per_tribe", "_mainMercenaryPerTribe"),
    ("is_force_stackable", "_isForceStackable"),
    ("is_sellable", "_isSellable"),
    ("use_camp_level", "_useCampLevel"),
    ("apply_equip_item_stat", "_applyEquipItemStat"),
    ("spawn_position_type", "_spawnPositionType"),
];
