// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Each entry maps the Rust struct field name (snake_case, what shape='v3'
// emits today) to the canonical Pearl Abyss C++ identifier (with leading
// underscore, what shape='v3.1' emits). Mechanical transliteration:
// snake_case → prepend `_` + lowerCamelCase. v3 names are NEVER overwritten;
// these aliases just enable v3.1 consumers (DMM v2.0.0-beta etc.) to request
// the canonical names.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("default_limit_summon_count", "_defaultLimitSummonCount"),
    ("default_limit_hire_count", "_defaultLimitHireCount"),
    ("max_limit_hire_count", "_maxLimitHireCount"),
    ("far_from_leader_option", "_farFromLeaderOption"),
    ("combat_targeting_flags", "_combatTargetingFlags"),
    ("is_controllable", "_isControllable"),
    ("is_playable", "_isPlayable"),
    ("set_new_mercenary_is_main", "_setNewMercenaryIsMain"),
    ("main_mercenary_per_tribe", "_mainMercenaryPerTribe"),
    ("is_force_stackable", "_isForceStackable"),
    ("is_sellable", "_isSellable"),
    ("use_camp_level", "_useCampLevel"),
    ("apply_equip_item_stat", "_applyEquipItemStat"),
    ("spawn_position_type", "_spawnPositionType"),
    ("mercenary_type", "_mercenaryType"),
    ("is_growable", "_isGrowable"),
    ("parent_mercenary_group_info", "_parentMercenaryGroupInfo"),
    ("hired_skill_info_list", "_hiredSkillInfoList"),
];
