// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Each entry maps the Rust struct field name (snake_case, what shape='v3'
// emits today) to the canonical Pearl Abyss C++ identifier (with leading
// underscore, what shape='v3.1' emits). Mechanical transliteration:
// snake_case → prepend `_` + lowerCamelCase. v3 names are NEVER overwritten;
// these aliases just enable v3.1 consumers (DMM v2.0.0-beta etc.) to request
// the canonical names.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("sound_event", "_soundEvent"),
    ("foot_step_sound_event", "_footStepSoundEvent"),
    ("foot_step_crouch_sound_event", "_footStepCrouchSoundEvent"),
    ("foot_step_land_sound_event", "_footStepLandSoundEvent"),
    ("foot_step_ground_sound_event", "_footStepGroundSoundEvent"),
    ("foot_step_sound_offset", "_footStepSoundOffset"),
    ("foot_step_crouch_sound_offset", "_footStepCrouchSoundOffset"),
    ("foot_step_land_sound_offset", "_footStepLandSoundOffset"),
    ("foot_step_ground_sound_offset", "_footStepGroundSoundOffset"),
    ("gender", "_gender"),
    ("character_age", "_characterAge"),
    ("job_info_list", "_jobInfoList"),
];
