// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Each entry maps the Rust struct field name (snake_case, what shape='v3'
// emits today) to the canonical Pearl Abyss C++ identifier (with leading
// underscore, what shape='v3.1' emits). Mechanical transliteration:
// snake_case → prepend `_` + lowerCamelCase. v3 names are NEVER overwritten;
// these aliases just enable v3.1 consumers (DMM v2.0.0-beta etc.) to request
// the canonical names.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("name", "_name"),
    ("stage_desc", "_stageDesc"),
    ("complete_log", "_completeLog"),
    ("sequencer_desc", "_sequencerDesc"),
    ("spawn_faction_spawn_data_info", "_spawnFactionSpawnDataInfo"),
    ("spawn_faction_node_info", "_spawnFactionNodeInfo"),
    ("disable_faction_spawn_party_name_hash_list", "_disableFactionSpawnPartyNameHashList"),
    ("list_a", "_listA"),
    ("close_filter_a", "_closeFilterA"),
    ("close_filter_b", "_closeFilterB"),
    ("close_filter_c", "_closeFilterC"),
    ("filter_entry_list", "_filterEntryList"),
    ("list_b", "_listB"),
    ("list_c", "_listC"),
    ("unk_new_carray_a", "_unkNewCarrayA"),
    ("unk_new_cbytes", "_unkNewCbytes"),
    ("unk_new_carray_b", "_unkNewCarrayB"),
    ("cstring_a", "_cstringA"),
    ("pair_a", "_pairA"),
    ("pair_b", "_pairB"),
    ("mob_map_list", "_mobMapList"),
    ("string_entry_list", "_stringEntryList"),
    ("adjacency_mob_list_a", "_adjacencyMobListA"),
    ("adjacency_mob_list_b", "_adjacencyMobListB"),
    ("adjacency_mob_list_c", "_adjacencyMobListC"),
    ("adjacency_mob_list_d", "_adjacencyMobListD"),
    ("close_filter_d_a", "_closeFilterDA"),
    ("close_filter_d_b", "_closeFilterDB"),
    ("close_filter_d_c", "_closeFilterDC"),
    ("close_filter_d_d", "_closeFilterDD"),
    ("list_d", "_listD"),
    ("platform_entry", "_platformEntry"),
    ("label_b", "_labelB"),
    ("behavior_entry_list", "_behaviorEntryList"),
];
