// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Schema-verified: each canonical name was matched against
// NattKh/CrimsonDesertModdingTools `pabgb_complete_schema.json`
// (canonical PA identifiers extracted from Korean error strings
// in CrimsonDesert.exe). Only fields whose mechanical snake→camel
// translation matched a known canonical name were shipped.
//
// v3 (snake_case) is the default emit; v3.1 emits the canonical `_camelCase`
// form. Round-trips identically — both names accepted on input.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("name", "_name"),
    ("stage_desc", "_stageDesc"),
    ("complete_log", "_completeLog"),
    ("sequencer_desc", "_sequencerDesc"),
    ("spawn_faction_spawn_data_info", "_spawnFactionSpawnDataInfo"),
    ("spawn_faction_node_info", "_spawnFactionNodeInfo"),
    ("disable_faction_spawn_party_name_hash_list", "_disableFactionSpawnPartyNameHashList"),
    ("raw_i", "_completeCount"),
];
