// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Each entry maps the Rust struct field name (snake_case, what shape='v3'
// emits today) to the canonical Pearl Abyss C++ identifier (with leading
// underscore, what shape='v3.1' emits). Mechanical transliteration:
// snake_case → prepend `_` + lowerCamelCase. v3 names are NEVER overwritten;
// these aliases just enable v3.1 consumers (DMM v2.0.0-beta etc.) to request
// the canonical names.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("group_name", "_groupName"),
    ("group_leader_info", "_groupLeaderInfo"),
    ("loading_target", "_loadingTarget"),
    ("behavior_optional", "_behaviorOptional"),
    ("use_reserve", "_useReserve"),
    ("ignore_player_state", "_ignorePlayerState"),
    ("player_behavior_space_radius", "_playerBehaviorSpaceRadius"),
    ("player_behavior_floor_check_distance", "_playerBehaviorFloorCheckDistance"),
    ("player_behavior_space_check_offset_y", "_playerBehaviorSpaceCheckOffsetY"),
    ("player_behavior_play_condition", "_playerBehaviorPlayCondition"),
    ("sequencer_desc_list", "_sequencerDescList"),
];
