// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Schema-verified: each canonical name was matched against
// NattKh/CrimsonDesertModdingTools `pabgb_complete_schema.json`
// (canonical PA identifiers extracted from Korean error strings
// in CrimsonDesert.exe). Only fields whose mechanical snake→camel
// translation matched a known canonical name were shipped.
//
// v3 (snake_case) is the default emit; v3.1 emits the canonical `_camelCase`
// form. Round-trips identically — both names accepted on input.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("group_name", "_groupName"),
    ("group_leader_info", "_groupLeaderInfo"),
    ("use_reserve", "_useReserve"),
    ("ignore_player_state", "_ignorePlayerState"),
    ("player_behavior_space_radius", "_playerBehaviorSpaceRadius"),
    ("player_behavior_floor_check_distance", "_playerBehaviorFloorCheckDistance"),
    ("player_behavior_space_check_offset_y", "_playerBehaviorSpaceCheckOffsetY"),
    ("player_behavior_play_condition", "_playerBehaviorPlayCondition"),
    ("sequencer_desc_list", "_sequencerDescList"),
];
