// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Schema-verified: each canonical name was matched against
// NattKh/CrimsonDesertModdingTools `pabgb_complete_schema.json`
// (canonical PA identifiers extracted from Korean error strings
// in CrimsonDesert.exe). Only fields whose mechanical snake→camel
// translation matched a known canonical name were shipped.
//
// v3 (snake_case) is the default emit; v3.1 emits the canonical `_camelCase`
// form. Round-trips identically — both names accepted on input.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("time_limit", "_timeLimit"),
    ("cool_time", "_coolTime"),
    ("auto_use_item_info", "_autoUseItemInfo"),
    ("convert_item_info", "_convertItemInfo"),
    ("fill_data_list", "_fillDataList"),
    ("memo", "_memo"),
    ("reserve_slot_type", "_reserveSlotType"),
    ("using_type", "_usingType"),
    ("enable_tribe_list", "_enableTribeList"),
    // 1.10: _enableVehicleList removed; _enableReserveSlotList + _reserveSlotTargetList added.
    ("enable_mercenary_list", "_enableMercenaryList"),
    ("enable_special_name_hash_list", "_enableSpecialNameHashList"),
    ("enable_reserve_slot_list", "_enableReserveSlotList"),
    ("target_item_group_list", "_enableItemGroupList"),
    ("reserve_slot_target_list", "_reserveSlotTargetList"),
    ("send_gimmick_event_key_for_slot_data_changed", "_sendGimmickEventKeyForSlotDataChanged"),
    ("is_self_player_only", "_isSelfPlayerOnly"),
    ("restore_on_retry", "_restoreOnRetry"),
];
