// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Each entry maps the Rust struct field name (snake_case, what shape='v3'
// emits today) to the canonical Pearl Abyss C++ identifier (with leading
// underscore, what shape='v3.1' emits). Mechanical transliteration:
// snake_case → prepend `_` + lowerCamelCase. v3 names are NEVER overwritten;
// these aliases just enable v3.1 consumers (DMM v2.0.0-beta etc.) to request
// the canonical names.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("ui_texture_name", "_uiTextureName"),
    ("is_default", "_isDefault"),
    ("expand_mercenary_type", "_expandMercenaryType"),
    ("faction_info", "_factionInfo"),
    ("faction_node_info", "_factionNodeInfo"),
    ("skill_info", "_skillInfo"),
    ("character_info_list", "_characterInfoList"),
    ("gimmick_info_list", "_gimmickInfoList"),
    ("region_info_list", "_regionInfoList"),
    ("stage_info_list", "_stageInfoList"),
    ("is_show_ui", "_isShowUi"),
    ("is_show_ui_alert", "_isShowUiAlert"),
    ("is_legendary_animal", "_isLegendaryAnimal"),
    ("ui_component_name", "_uiComponentName"),
    ("knowledge_from_list", "_knowledgeFromList"),
    ("knowledge_group_list", "_knowledgeGroupList"),
    ("knowledge_level_data_list", "_knowledgeLevelDataList"),
    ("meditation_resource_list", "_meditationResourceList"),
    ("shared_level_main_knowledge_info", "_sharedLevelMainKnowledgeInfo"),
    ("shared_level_knowledge_info_list", "_sharedLevelKnowledgeInfoList"),
    ("knowledge_alias_map", "_knowledgeAliasMap"),
    ("item_info", "_itemInfo"),
    ("bitmap_color_r", "_bitmapColorR"),
    ("learning_position", "_learningPosition"),
    ("learning_stage_info", "_learningStageInfo"),
    ("learn_apply_skill_info", "_learnApplySkillInfo"),
    ("level_gimmick_scene_object_data_list", "_levelGimmickSceneObjectDataList"),
];
