// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Schema-verified: each canonical name was matched against
// NattKh/CrimsonDesertModdingTools `pabgb_complete_schema.json`
// (canonical PA identifiers extracted from Korean error strings
// in CrimsonDesert.exe). Only fields whose mechanical snake→camel
// translation matched a known canonical name were shipped.
//
// v3 (snake_case) is the default emit; v3.1 emits the canonical `_camelCase`
// form. Round-trips identically — both names accepted on input.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("ui_texture_name", "_uiTextureName"),
    ("is_default", "_isDefault"),
    ("expand_mercenary_type", "_expandMercenaryType"),
    ("faction_info", "_factionInfo"),
    ("faction_node_info", "_factionNodeInfo"),
    ("skill_info", "_skillInfo"),
    ("character_info_list", "_characterInfoList"),
    ("gimmick_info_list", "_gimmickInfoList"),
    ("region_info_list", "_regionInfoList"),
    ("stage_info_list", "_stageInfoList"),
    ("is_show_ui", "_isShowUI"),
    ("is_show_ui_alert", "_isShowUIAlert"),
    ("is_legendary_animal", "_isLegendaryAnimal"),
    ("ui_component_name", "_uiComponentName"),
    ("knowledge_from_list", "_knowledgeFromList"),
    ("knowledge_group_list", "_knowledgeGroupList"),
    ("knowledge_level_data_list", "_knowledgeLevelDataList"),
    ("meditation_resource_list", "_meditationResourceList"),
    ("shared_level_main_knowledge_info", "_sharedLevelMainKnowledgeInfo"),
    ("shared_level_knowledge_info_list", "_sharedLevelKnowledgeInfoList"),
    ("knowledge_alias_map", "_knowledgeAliasMap"),
    ("item_info", "_itemInfo"),
    ("bitmap_color_r", "_bitmapColorR"),
    ("learning_position", "_learningPosition"),
    ("learning_stage_info", "_learningStageInfo"),
    ("learn_apply_skill_info", "_learnApplySkillInfo"),
    ("level_gimmick_scene_object_data_list", "_linkKnowledgeNodeList"),
];
