// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Schema-verified: each canonical name was matched against
// NattKh/CrimsonDesertModdingTools `pabgb_complete_schema.json`
// (canonical PA identifiers extracted from Korean error strings
// in CrimsonDesert.exe). Only fields whose mechanical snake→camel
// translation matched a known canonical name were shipped.
//
// v3 (snake_case) is the default emit; v3.1 emits the canonical `_camelCase`
// form. Round-trips identically — both names accepted on input.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("parent_quest", "_parentQuest"),
    ("sub_mission_list", "_subMissionList"),
    ("branch_mission_list", "_branchMissionList"),
    ("execute_stage_list", "_executeStageList"),
    ("start_player_list", "_startPlayerList"),
    ("field_revive_list", "_fieldReviveList"),
    ("give_up_field_revive_list", "_giveUpFieldReviveList"),
    ("trigger_volume_data", "_triggerVolumeData"),
    ("reward_list", "_rewardList"),
    ("result_data_list", "_resultDataList"),
    ("reward_inventory_key", "_rewardInventoryKey"),
    ("ui_desc", "_uiDesc"),
    ("label_a", "_completeName"),
    ("label_b", "_name"),
    ("label_c", "_completeLog"),
    ("label_d", "_desc"),
];
