// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Each entry maps the Rust struct field name (snake_case, what shape='v3'
// emits today) to the canonical Pearl Abyss C++ identifier (with leading
// underscore, what shape='v3.1' emits). Mechanical transliteration:
// snake_case → prepend `_` + lowerCamelCase. v3 names are NEVER overwritten;
// these aliases just enable v3.1 consumers (DMM v2.0.0-beta etc.) to request
// the canonical names.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("parent_quest", "_parentQuest"),
    ("sub_mission_list", "_subMissionList"),
    ("branch_mission_list", "_branchMissionList"),
    ("execute_stage_list", "_executeStageList"),
    ("start_player_list", "_startPlayerList"),
    ("field_revive_list", "_fieldReviveList"),
    ("give_up_field_revive_list", "_giveUpFieldReviveList"),
    ("trigger_volume_data", "_triggerVolumeData"),
    ("reward_list", "_rewardList"),
    ("result_data_list", "_resultDataList"),
    ("reward_inventory_key", "_rewardInventoryKey"),
    ("ui_desc", "_uiDesc"),
    ("label_a", "_labelA"),
    ("label_b", "_labelB"),
    ("label_c", "_labelC"),
    ("label_d", "_labelD"),
    ("result_data_2_lookup", "_resultData2Lookup"),
    ("result_data_list_2", "_resultDataList2"),
    ("mission_stage_list", "_missionStageList"),
    ("category_info", "_categoryInfo"),
    ("raw_418", "_raw418"),
    ("raw_420", "_raw420"),
    ("raw_424", "_raw424"),
    ("flag_428", "_flag428"),
    ("flag_429", "_flag429"),
    ("flag_430", "_flag430"),
    ("flag_431", "_flag431"),
    ("flag_432", "_flag432"),
    ("flag_433", "_flag433"),
    ("flag_434", "_flag434"),
    ("flag_435", "_flag435"),
    ("flag_436", "_flag436"),
    ("flag_437", "_flag437"),
    ("flag_438", "_flag438"),
    ("flag_439", "_flag439"),
    ("flag_440", "_flag440"),
    ("trailing_u32", "_trailingU32"),
];
