// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Each entry maps the Rust struct field name (snake_case, what shape='v3'
// emits today) to the canonical Pearl Abyss C++ identifier (with leading
// underscore, what shape='v3.1' emits). Mechanical transliteration:
// snake_case → prepend `_` + lowerCamelCase. v3 names are NEVER overwritten;
// these aliases just enable v3.1 consumers (DMM v2.0.0-beta etc.) to request
// the canonical names.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("elemental_material_system_type", "_elementalMaterialSystemType"),
    ("elemental_material_key", "_elementalMaterialKey"),
    ("unk_new_u32_a", "_unkNewU32A"),
    ("unk_new_u32_b", "_unkNewU32B"),
    ("total_fuel_amount", "_totalFuelAmount"),
    ("fuel_standard_obb_size", "_fuelStandardObbSize"),
    ("fuel_end_passive_skill_key", "_fuelEndPassiveSkillKey"),
    ("fuel_end_passive_skill_level", "_fuelEndPassiveSkillLevel"),
    ("fuel_end_active_skill_key", "_fuelEndActiveSkillKey"),
    ("fuel_end_active_skill_level", "_fuelEndActiveSkillLevel"),
    ("use_temperature_transfer_margin", "_useTemperatureTransferMargin"),
    ("elemental_material_state_data_list", "_elementalMaterialStateDataList"),
    ("min_stat_list", "_minStatList"),
    ("max_stat_list", "_maxStatList"),
    ("parent_material_key_list_deprecated_xxx", "_parentMaterialKeyListDeprecatedXxx"),
    ("flag_0", "_flag0"),
    ("flag_1", "_flag1"),
    ("flag_2", "_flag2"),
    ("flag_3", "_flag3"),
    ("flag_4", "_flag4"),
    ("flag_5", "_flag5"),
    ("flag_6", "_flag6"),
    ("flag_7", "_flag7"),
    ("is_system_type", "_isSystemType"),
    ("elemental_material_stat_data_list", "_elementalMaterialStatDataList"),
    ("scene_object_spawnable_type", "_sceneObjectSpawnableType"),
];
