// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Schema-verified: each canonical name was matched against
// NattKh/CrimsonDesertModdingTools `pabgb_complete_schema.json`
// (canonical PA identifiers extracted from Korean error strings
// in CrimsonDesert.exe). Only fields whose mechanical snake→camel
// translation matched a known canonical name were shipped.
//
// v3 (snake_case) is the default emit; v3.1 emits the canonical `_camelCase`
// form. Round-trips identically — both names accepted on input.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("elemental_material_system_type", "_elementalMaterialSystemType"),
    ("elemental_material_key", "_elementalMaterialKey"),
    ("total_fuel_amount", "_totalFuelAmount"),
    ("fuel_standard_obb_size", "_fuelStandardObbSize"),
    ("fuel_end_passive_skill_key", "_fuelEndPassiveSkillKey"),
    ("fuel_end_passive_skill_level", "_fuelEndPassiveSkillLevel"),
    ("fuel_end_active_skill_key", "_fuelEndActiveSkillKey"),
    ("fuel_end_active_skill_level", "_fuelEndActiveSkillLevel"),
    ("use_temperature_transfer_margin", "_useTemperatureTransferMargin"),
    ("elemental_material_state_data_list", "_elementalMaterialStateDataList"),
    ("min_stat_list", "_minStatList"),
    ("max_stat_list", "_maxStatList"),
    ("parent_material_key_list_deprecated_xxx", "_parentMaterialKeyListDeprecatedXXX"),
    ("is_system_type", "_isSystemType"),
    ("elemental_material_stat_data_list", "_elementalMaterialStatDataList"),
    ("scene_object_spawnable_type", "_sceneObjectSpawnableType"),
];
