// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Each entry maps the Rust struct field name (snake_case, what shape='v3'
// emits today) to the canonical Pearl Abyss C++ identifier (with leading
// underscore, what shape='v3.1' emits). Mechanical transliteration:
// snake_case → prepend `_` + lowerCamelCase. v3 names are NEVER overwritten;
// these aliases just enable v3.1 consumers (DMM v2.0.0-beta etc.) to request
// the canonical names.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("condition", "_condition"),
    ("projectile_key", "_projectileKey"),
    ("projectile_shot_key", "_projectileShotKey"),
    ("projectile_chase_physics_material_hash", "_projectileChasePhysicsMaterialHash"),
    ("projectile_shot_spread", "_projectileShotSpread"),
    ("projectile_shot_interval", "_projectileShotInterval"),
    ("projectile_height_offset", "_projectileHeightOffset"),
    ("projectile_create_delay_time", "_projectileCreateDelayTime"),
    ("projectile_hit_rate", "_projectileHitRate"),
    ("projectile_shot_count", "_projectileShotCount"),
    ("effect_data", "_effectData"),
    ("weather_data", "_weatherData"),
    ("post_process_data", "_postProcessData"),
    ("is_advanced", "_isAdvanced"),
];
