// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Schema-verified: each canonical name was matched against
// NattKh/CrimsonDesertModdingTools `pabgb_complete_schema.json`
// (canonical PA identifiers extracted from Korean error strings
// in CrimsonDesert.exe). Only fields whose mechanical snake→camel
// translation matched a known canonical name were shipped.
//
// v3 (snake_case) is the default emit; v3.1 emits the canonical `_camelCase`
// form. Round-trips identically — both names accepted on input.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("condition", "_condition"),
    ("projectile_key", "_projectileKey"),
    ("projectile_shot_key", "_projectileShotKey"),
    ("projectile_chase_physics_material_hash", "_projectileChasePhysicsMaterialHash"),
    ("projectile_shot_spread", "_projectileShotSpread"),
    ("projectile_shot_interval", "_projectileShotInterval"),
    ("projectile_height_offset", "_projectileHeightOffset"),
    ("projectile_create_delay_time", "_projectileCreateDelayTime"),
    ("projectile_hit_rate", "_projectileHitRate"),
    ("projectile_shot_count", "_projectileShotCount"),
    ("effect_data", "_effectData"),
    ("weather_data", "_weatherData"),
    ("post_process_data", "_postProcessData"),
    ("is_advanced", "_isAdvanced"),
];
