// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Schema-verified: each canonical name was matched against
// NattKh/CrimsonDesertModdingTools `pabgb_complete_schema.json`
// (canonical PA identifiers extracted from Korean error strings
// in CrimsonDesert.exe). Only fields whose mechanical snake→camel
// translation matched a known canonical name were shipped.
//
// v3 (snake_case) is the default emit; v3.1 emits the canonical `_camelCase`
// form. Round-trips identically — both names accepted on input.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("title_local_string_info", "_titleLocalStringInfo"),
    ("desc_local_string_info", "_descLocalStringInfo"),
    ("key_mouse_input_desc_local_string_info", "_keyMouseInputDescLocalStringInfo"),
    ("game_advice_unknown_name", "_gameAdviceUnknownName"),
    ("ui_texture_name_string_info", "_uiTextureNameStringInfo"),
    ("ui_video_path_string_info", "_uiVideoPathStringInfo"),
    ("widget_id_string_info", "_widgetIdStringInfo"),
    ("is_once", "_isOnce"),
    ("is_show_guide_list", "_isShowGuideList"),
    ("game_advice_group_info", "_gameAdviceGroupInfo"),
    ("is_default", "_isDefault"),
    ("is_use_loading_view", "_isUseLoadingView"),
];
