// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Each entry maps the Rust struct field name (snake_case, what shape='v3'
// emits today) to the canonical Pearl Abyss C++ identifier (with leading
// underscore, what shape='v3.1' emits). Mechanical transliteration:
// snake_case → prepend `_` + lowerCamelCase. v3 names are NEVER overwritten;
// these aliases just enable v3.1 consumers (DMM v2.0.0-beta etc.) to request
// the canonical names.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("title_local_string_info", "_titleLocalStringInfo"),
    ("desc_local_string_info", "_descLocalStringInfo"),
    ("key_mouse_input_desc_local_string_info", "_keyMouseInputDescLocalStringInfo"),
    ("game_advice_unknown_name", "_gameAdviceUnknownName"),
    ("ui_texture_name_string_info", "_uiTextureNameStringInfo"),
    ("ui_video_path_string_info", "_uiVideoPathStringInfo"),
    ("widget_id_string_info", "_widgetIdStringInfo"),
    ("sort_order", "_sortOrder"),
    ("is_once", "_isOnce"),
    ("is_show_guide_list", "_isShowGuideList"),
    ("game_advice_group_info", "_gameAdviceGroupInfo"),
    ("is_default", "_isDefault"),
    ("is_use_loading_view", "_isUseLoadingView"),
];
