// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Schema-verified: each canonical name was matched against
// NattKh/CrimsonDesertModdingTools `pabgb_complete_schema.json`
// (canonical PA identifiers extracted from Korean error strings
// in CrimsonDesert.exe). Only fields whose mechanical snake→camel
// translation matched a known canonical name were shipped.
//
// v3 (snake_case) is the default emit; v3.1 emits the canonical `_camelCase`
// form. Round-trips identically — both names accepted on input.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("quest_type", "_questType"),
    ("quest_category", "_questCategory"),
    ("name", "_name"),
    ("desc", "_desc"),
    ("quest_group_info", "_questGroupInfo"),
    ("faction_info", "_factionInfo"),
    ("faction_state_data", "_factionStateData"),
    ("branch_data", "_branchData"),
    ("start_player_list", "_startPlayerList"),
    ("branch_data_list", "_branchDataList"),
    ("executor_quest_list", "_executorQuestList"),
    ("gauge_list", "_gaugeList"),
    ("mission_list", "_missionList"),
    ("stage_list", "_stageList"),
    ("start_mission", "_startMission"),
    ("start_stage", "_startStage"),
    ("stage_icon_path", "_stageIconPath"),
    ("stage_text_icon_path", "_stageTextIconPath"),
    ("stage_image_path", "_stageImagePath"),
    ("playable_mission_count", "_playableMissionCount"),
    ("playable_stage_count", "_playableStageCount"),
    ("test_tag", "_testTag"),
    ("game_start_stage", "_gameStartStage"),
    ("game_start_sub_timeline", "_gameStartSubTimeline"),
    ("memo", "_memo"),
    ("quest_dialog_filter_data_list", "_questDialogFilterDataList"),
    ("dialog_must_mission_info_list", "_dialogMustMissionInfoList"),
    ("npc_dialog_must_condition", "_npcDialogMustCondition"),
    ("is_save", "_isSave"),
    ("is_continuous_mission", "_isContinuousMission"),
    ("debug_color", "_debugColor"),
];
