// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Schema-verified: each canonical name was matched against
// NattKh/CrimsonDesertModdingTools `pabgb_complete_schema.json`
// (canonical PA identifiers extracted from Korean error strings
// in CrimsonDesert.exe). Only fields whose mechanical snake→camel
// translation matched a known canonical name were shipped.
//
// v3 (snake_case) is the default emit; v3.1 emits the canonical `_camelCase`
// form. Round-trips identically — both names accepted on input.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("use_resource_item_type", "_useResourceItemType"),
    ("fake_equip_reserve_slot_data", "_fakeEquipReserveSlotData"),
    ("apply_status_group_info_on_activate", "_applyStatusGroupInfoOnActivate"),
    ("apply_passive_skill_on_activate", "_applyPassiveSkillOnActivate"),
    ("is_show_stamina", "_isShowStamina"),
    ("decrease_endurance_percent", "_decreaseEndurancePercent"),
    ("on_guard_damage_reduction_percent", "_onGuardDamageReductionPercent"),
    ("is_critical_collidable", "_isCriticalCollidable"),
    ("enable_transfer", "_enableTransfer"),
    ("enable_enchant", "_enableEnchant"),
    ("use_action_on_quick_slot", "_useActionOnQuickSlot"),
    ("camera_preset_hash", "_cameraPresetHash"),
    ("dye_rotation_value", "_dyeRotationValue"),
    ("equip_able_hash_list", "_equipAbleHashList"),
    ("equip_type_name", "_equipTypeName"),
    ("show_helm_on_battle_stance", "_showHelmOnBattleStance"),
];
