// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Each entry maps the Rust struct field name (snake_case, what shape='v3'
// emits today) to the canonical Pearl Abyss C++ identifier (with leading
// underscore, what shape='v3.1' emits). Mechanical transliteration:
// snake_case → prepend `_` + lowerCamelCase. v3 names are NEVER overwritten;
// these aliases just enable v3.1 consumers (DMM v2.0.0-beta etc.) to request
// the canonical names.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("destroyed_ai_event_head", "_destroyedAiEventHead"),
    ("destroyed_ai_event_pad", "_destroyedAiEventPad"),
    ("destroyed_ai_event_hash", "_destroyedAiEventHash"),
    ("destroyed_ai_event_tail", "_destroyedAiEventTail"),
    ("use_resource_item_type", "_useResourceItemType"),
    ("fake_equip_reserve_slot_data", "_fakeEquipReserveSlotData"),
    ("apply_status_group_info_on_activate", "_applyStatusGroupInfoOnActivate"),
    ("apply_passive_skill_on_activate", "_applyPassiveSkillOnActivate"),
    ("is_show_stamina", "_isShowStamina"),
    ("decrease_endurance_percent", "_decreaseEndurancePercent"),
    ("on_guard_damage_reduction_percent", "_onGuardDamageReductionPercent"),
    ("is_critical_collidable", "_isCriticalCollidable"),
    ("enable_transfer", "_enableTransfer"),
    ("enable_enchant", "_enableEnchant"),
    ("use_action_on_quick_slot", "_useActionOnQuickSlot"),
    ("camera_preset_hash", "_cameraPresetHash"),
    ("dye_rotation_value", "_dyeRotationValue"),
    ("equip_able_hash_list", "_equipAbleHashList"),
    ("equip_type_name", "_equipTypeName"),
    ("show_helm_on_battle_stance", "_showHelmOnBattleStance"),
];
