// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Each entry maps the Rust struct field name (snake_case, what shape='v3'
// emits today) to the canonical Pearl Abyss C++ identifier (with leading
// underscore, what shape='v3.1' emits). Mechanical transliteration:
// snake_case → prepend `_` + lowerCamelCase. v3 names are NEVER overwritten;
// these aliases just enable v3.1 consumers (DMM v2.0.0-beta etc.) to request
// the canonical names.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("cooltime", "_cooltime"),
    ("buff_level_list", "_buffLevelList"),
    ("skill_group_key", "_skillGroupKey"),
    ("parent_skill", "_parentSkill"),
    ("learn_level", "_learnLevel"),
    ("apply_type", "_applyType"),
    ("icon_path", "_iconPath"),
    ("need_upgrade_item_info", "_needUpgradeItemInfo"),
    ("need_upgrade_item_count_graph", "_needUpgradeItemCountGraph"),
    ("need_upgrade_experience_graph", "_needUpgradeExperienceGraph"),
    ("usable_character_info_list", "_usableCharacterInfoList"),
    ("usable_condition", "_usableCondition"),
    ("learn_knowledge_info", "_learnKnowledgeInfo"),
    ("faction_info", "_factionInfo"),
    ("use_resource_stat_list", "_useResourceStatList"),
    ("use_resource_item_list", "_useResourceItemList"),
    ("use_driver_resource_stat_list", "_useDriverResourceStatList"),
    ("use_battery_stat", "_useBatteryStat"),
    ("is_ui_use_allowed", "_isUiUseAllowed"),
    ("is_learn_use_artifact", "_isLearnUseArtifact"),
    ("allow_skill_with_low_resource", "_allowSkillWithLowResource"),
    ("is_use_child_pattern_description_buff_data", "_isUseChildPatternDescriptionBuffData"),
    ("damage_type", "_damageType"),
    ("ui_type", "_uiType"),
    ("reserve_slot_info_list", "_reserveSlotInfoList"),
    ("max_level", "_maxLevel"),
    ("skill_group_key_list", "_skillGroupKeyList"),
    ("buff_sustain_flag", "_buffSustainFlag"),
    ("dev_skill_name", "_devSkillName"),
    ("dev_skill_desc", "_devSkillDesc"),
    ("video_path", "_videoPath"),
];
