// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Each entry maps the Rust struct field name (snake_case, what shape='v3'
// emits today) to the canonical Pearl Abyss C++ identifier (with leading
// underscore, what shape='v3.1' emits). Mechanical transliteration:
// snake_case → prepend `_` + lowerCamelCase. v3 names are NEVER overwritten;
// these aliases just enable v3.1 consumers (DMM v2.0.0-beta etc.) to request
// the canonical names.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("buff_data_list", "_buffDataList"),
    ("min_level", "_minLevel"),
    ("max_level", "_maxLevel"),
    ("sequencer_file_name", "_sequencerFileName"),
    ("buff_level_calculate_type", "_buffLevelCalculateType"),
    ("ui_template_name", "_uiTemplateName"),
    ("ui_component_name", "_uiComponentName"),
    ("elemental_status_info", "_elementalStatusInfo"),
    ("is_use_skill_info_pattern_description", "_isUseSkillInfoPatternDescription"),
    ("use_counting_by_global_timer", "_useCountingByGlobalTimer"),
];
