// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Schema-verified: each canonical name was matched against
// NattKh/CrimsonDesertModdingTools `pabgb_complete_schema.json`
// (canonical PA identifiers extracted from Korean error strings
// in CrimsonDesert.exe). Only fields whose mechanical snake→camel
// translation matched a known canonical name were shipped.
//
// v3 (snake_case) is the default emit; v3.1 emits the canonical `_camelCase`
// form. Round-trips identically — both names accepted on input.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("buff_data_list", "_buffDataList"),
    ("min_level", "_minLevel"),
    ("max_level", "_maxLevel"),
    ("sequencer_file_name", "_sequencerFileName"),
    ("buff_level_calculate_type", "_buffLevelCalculateType"),
    ("ui_template_name", "_uiTemplateName"),
    ("ui_component_name", "_uiComponentName"),
    ("elemental_status_info", "_elementalStatusInfo"),
    ("is_use_skill_info_pattern_description", "_isUseSkillInfoPatternDescription"),
    ("use_counting_by_global_timer", "_useCountingByGlobalTimer"),
];
