// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Each entry maps the Rust struct field name (snake_case, what shape='v3'
// emits today) to the canonical Pearl Abyss C++ identifier (with leading
// underscore, what shape='v3.1' emits). Mechanical transliteration:
// snake_case → prepend `_` + lowerCamelCase. v3 names are NEVER overwritten;
// these aliases just enable v3.1 consumers (DMM v2.0.0-beta etc.) to request
// the canonical names.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("type_", "_type"),
    ("active_condition_info", "_activeConditionInfo"),
    ("post_process_sequencer_name", "_postProcessSequencerName"),
    ("time_scale", "_timeScale"),
    ("player_time_scale", "_playerTimeScale"),
    ("mode_radius", "_modeRadius"),
    ("passive_skill", "_passiveSkill"),
    ("skill_level", "_skillLevel"),
    ("input_key_hash", "_inputKeyHash"),
    ("cancel_input_key_hash", "_cancelInputKeyHash"),
    ("has_near_by_target_option", "_hasNearByTargetOption"),
    ("is_high_priority", "_isHighPriority"),
    ("exclusive_with_detect", "_exclusiveWithDetect"),
    ("disable_occlusion_culling", "_disableOcclusionCulling"),
    ("disable_player_targetable", "_disablePlayerTargetable"),
    ("change_minimap_scale", "_changeMinimapScale"),
    ("is_minimap_zoom_out", "_isMinimapZoomOut"),
    ("is_allow_dialog", "_isAllowDialog"),
    ("option_slots", "_optionSlots"),
    ("detect_mode_area_data", "_detectModeAreaData"),
    ("player_action_limit_desc", "_playerActionLimitDesc"),
];
