// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Schema-verified: each canonical name was matched against
// NattKh/CrimsonDesertModdingTools `pabgb_complete_schema.json`
// (canonical PA identifiers extracted from Korean error strings
// in CrimsonDesert.exe). Only fields whose mechanical snake→camel
// translation matched a known canonical name were shipped.
//
// v3 (snake_case) is the default emit; v3.1 emits the canonical `_camelCase`
// form. Round-trips identically — both names accepted on input.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("type_", "_type"),
    ("active_condition_info", "_activeConditionInfo"),
    ("post_process_sequencer_name", "_postProcessSequencerName"),
    ("time_scale", "_timeScale"),
    ("player_time_scale", "_playerTimeScale"),
    ("mode_radius", "_modeRadius"),
    ("passive_skill", "_passiveSkill"),
    ("skill_level", "_skillLevel"),
    ("input_key_hash", "_inputKeyHash"),
    ("cancel_input_key_hash", "_cancelInputKeyHash"),
    ("has_near_by_target_option", "_hasNearByTargetOption"),
    ("is_high_priority", "_isHighPriority"),
    ("exclusive_with_detect", "_exclusiveWithDetect"),
    ("disable_occlusion_culling", "_disableOcclusionCulling"),
    ("disable_player_targetable", "_disablePlayerTargetable"),
    ("change_minimap_scale", "_changeMinimapScale"),
    ("is_minimap_zoom_out", "_isMinimapZoomOut"),
    ("is_allow_dialog", "_isAllowDialog"),
    ("option_slots", "_optionList"),
    ("detect_mode_area_data", "_detectModeAreaData"),
    ("player_action_limit_desc", "_playerActionLimitDesc"),
];
