// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Each entry maps the Rust struct field name (snake_case, what shape='v3'
// emits today) to the canonical Pearl Abyss C++ identifier (with leading
// underscore, what shape='v3.1' emits). Mechanical transliteration:
// snake_case → prepend `_` + lowerCamelCase. v3 names are NEVER overwritten;
// these aliases just enable v3.1 consumers (DMM v2.0.0-beta etc.) to request
// the canonical names.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("unk_22", "_unk22"),
    ("unk_24", "_unk24"),
    ("unk_28", "_unk28"),
    ("unk_29", "_unk29"),
    ("unk_30", "_unk30"),
    ("unk_31", "_unk31"),
    ("unk_32", "_unk32"),
    ("unk_33", "_unk33"),
    ("unk_34", "_unk34"),
    ("unk_35", "_unk35"),
    ("unk_36", "_unk36"),
    ("unk_40", "_unk40"),
    ("unk_44", "_unk44"),
    ("unk_48", "_unk48"),
    ("unk_56", "_unk56"),
    ("unk_64", "_unk64"),
    ("unk_68", "_unk68"),
    ("unk_72", "_unk72"),
    ("unk_76", "_unk76"),
    ("unk_80", "_unk80"),
    ("unk_81", "_unk81"),
    ("unk_84", "_unk84"),
    ("unk_88", "_unk88"),
    ("ref_list", "_refList"),
];
