// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Schema-verified: each canonical name was matched against
// NattKh/CrimsonDesertModdingTools `pabgb_complete_schema.json`
// (canonical PA identifiers extracted from Korean error strings
// in CrimsonDesert.exe). Only fields whose mechanical snake→camel
// translation matched a known canonical name were shipped.
//
// v3 (snake_case) is the default emit; v3.1 emits the canonical `_camelCase`
// form. Round-trips identically — both names accepted on input.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("lookup_a", "_footStepTypeEffectName"),
    ("lookup_b", "_ignoredReactionInSafeZoneFlag"),
    ("unk_22", "_tribeMassLevel"),
    ("unk_28", "_wantedCrimeType"),
    ("unk_29", "_interactionUIDistanceLv"),
    ("unk_30", "_ignoreWaterFall"),
    ("unk_31", "_isBird"),
    ("unk_32", "_isHumanoid"),
    ("unk_33", "_hasChild"),
    ("unk_34", "_isDeathByDrowning"),
    ("unk_35", "_detourOnRoad"),
    ("unk_36", "_detectModeShowEnemy"),
    ("unk_56", "_tribeNameForEditor"),
    ("unk_80", "_escapePlatform"),
    ("unk_81", "_ignoreOverlapPush"),
    ("ref_list", "_tamedSkillList"),
];
