// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Schema-verified: each canonical name was matched against
// NattKh/CrimsonDesertModdingTools `pabgb_complete_schema.json`
// (canonical PA identifiers extracted from Korean error strings
// in CrimsonDesert.exe). Only fields whose mechanical snake→camel
// translation matched a known canonical name were shipped.
//
// v3 (snake_case) is the default emit; v3.1 emits the canonical `_camelCase`
// form. Round-trips identically — both names accepted on input.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("lookup_a", "_footStepTypeEffectName"),
    ("lookup_b", "_ignoredReactionInSafeZoneFlag"),
    ("unk_22", "_tribeMassLevel"),
    ("unk_24", "_bumpTypeHash"),
    ("unk_28", "_wantedCrimeType"),
    ("unk_29", "_interactionUIDistanceLv"),
    ("faction_patrol_spawn_distance_type", "_factionPatrolSpawnDistanceType"),
    ("unk_30", "_ignoreWaterFall"),
    ("unk_31", "_isBird"),
    ("unk_32", "_isHumanoid"),
    ("unk_33", "_hasChild"),
    ("unk_34", "_isDeathByDrowning"),
    ("unk_35", "_detourOnRoad"),
    ("unk_36", "_detectModeShowEnemy"),
    ("unk_40", "_footMaterialKey"),
    ("unk_44", "_characterPauseType"),
    ("unk_48", "_detourMaxDegree"),
    ("unk_56", "_tribeNameForEditor"),
    ("unk_64", "_velocityDampSpeed"),
    ("unk_68", "_activityWaterDepth"),
    ("unk_72", "_weaponMaterialKey"),
    ("unk_76", "_armorMaterialKey"),
    // ⚠ These four predate the 1.0.8 restructure and no longer match any
    // struct field (the region became unk_80_lo / unk_80_hi). Kept because
    // they record the canonical names for that byte range — and 1.18 confirms
    // the shape: the new byte lands exactly 4 bytes into unk_80_lo, i.e. on
    // the boundary these names imply (u8 _escapePlatform, u8
    // _ignoreOverlapPush, … then u32 _baseMaterialKey at +4).
    ("unk_80", "_escapePlatform"),
    ("unk_81", "_ignoreOverlapPush"),
    ("is_steering_movement", "_isSteeringMovement"),
    ("unk_84", "_baseMaterialKey"),
    ("unk_88", "_parentTribeInfo"),
    ("ref_list", "_tamedSkillList"),
];
