// Iter 6 of T0 verification loop (2026-05-11): hand-edited after IDA
// verification of the MercenaryGroupInfo metaobject at 0x144b0a300+.
// Originally auto-generated by scripts/generate_v3_1_aliases.py with
// mechanical snake → _camelCase translation; the script-generated
// `_mercenaryKeyList` was wrong because the canonical PA name is
// actually `_allowOperationTypeList`. Renamed both the rust struct
// field AND its alias here.
//
// v3 (snake_case) is the default emit; v3.1 emits the canonical `_camelCase`
// form. Round-trips identically — both names accepted on input.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("allow_operation_type_list", "_allowOperationTypeList"),
    // typo intentional in BOTH rust and PA binary (verified IDA 0x144b0a515)
    ("mercenarye_info_list", "_mercenaryeInfoList"),
    ("child_mercenary_group_info_list", "_childMercenaryGroupInfoList"),
    ("parent_mercenary_group_info", "_parentMercenaryGroupInfo"),
];
