// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Mechanical translation only: this table is not present in NattKh's
// pabgb_complete_schema.json, so canonical names could not be
// independently verified. Aliases are derived from the Rust struct
// field name via snake → `_camelCase` conversion.
//
// v3 (snake_case) is the default emit; v3.1 emits the canonical `_camelCase`
// form. Round-trips identically — both names accepted on input.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("mercenarye_info_list", "_mercenaryeInfoList"),
    ("child_mercenary_group_info_list", "_childMercenaryGroupInfoList"),
    ("allow_operation_type_list", "_allowOperationTypeList"),
    ("parent_mercenary_group_info", "_parentMercenaryGroupInfo"),
    ("is_dead_state_updatable", "_isDeadStateUpdatable"),
    ("is_using_portrait_texture", "_isUsingPortraitTexture"),
    ("is_item_contribution_countable", "_isItemContributionCountable"),
    ("is_hyosi_usable", "_isHyosiUsable"),
    ("use_chanage_main_mercenary", "_useChanageMainMercenary"),
    ("is_using_spawned_usable", "_isUsingSpawnedUsable"),
    ("use_reserve_or_main", "_useReserveOrMain"),
    ("use_vehicle_key", "_useVehicleKey"),
    ("is_return_main_mercenary_data", "_isReturnMainMercenaryData"),
];
