// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Mechanical translation only: this table is not present in NattKh's
// pabgb_complete_schema.json, so canonical names could not be
// independently verified. Aliases are derived from the Rust struct
// field name via snake → `_camelCase` conversion.
//
// v3 (snake_case) is the default emit; v3.1 emits the canonical `_camelCase`
// form. Round-trips identically — both names accepted on input.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("contents_phase_type", "_contentsPhaseType"),
    ("camera_preset_name_hash", "_cameraPresetNameHash"),
    ("camera_pivot_offset_y_ratio", "_cameraPivotOffsetYRatio"),
    ("active_cursor_mode", "_activeCursorMode"),
    ("play_global_stage_sequencer", "_playGlobalStageSequencer"),
    ("use_housing_placement", "_useHousingPlacement"),
    ("use_change_house", "_useChangeHouse"),
    ("housing_placement_limit", "_housingPlacementLimit"),
    ("button_ui_template_name", "_buttonUiTemplateName"),
    ("disable_button_ui_template_name", "_disableButtonUiTemplateName"),
    ("enable_button_ui_component_name", "_enableButtonUiComponentName"),
    ("disable_button_ui_component_name", "_disableButtonUiComponentName"),
];
