// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Schema-verified: each canonical name was matched against
// NattKh/CrimsonDesertModdingTools `pabgb_complete_schema.json`
// (canonical PA identifiers extracted from Korean error strings
// in CrimsonDesert.exe). Only fields whose mechanical snake→camel
// translation matched a known canonical name were shipped.
//
// v3 (snake_case) is the default emit; v3.1 emits the canonical `_camelCase`
// form. Round-trips identically — both names accepted on input.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("knowledge_info", "_knowledgeInfo"),
    ("skill_tree_info", "_skillTreeInfo"),
    ("connect_research_node_info", "_connectResearchNodeInfo"),
    ("store_info", "_storeInfo"),
    ("royal_supply_info", "_royalSupplyInfo"),
    ("memo", "_memo"),
    ("child_faction_info_list", "_childFactionInfoList"),
    ("node_line_main_faction_info_list", "_nodeLineMainFactionInfoList"),
    ("world_position", "_worldPosition"),
    ("node_radius", "_nodeRadius"),
    ("apply_skill_data_list", "_applySkillDataList"),
    ("resource_item_list", "_resourceItemList"),
    ("revival_stage_info_list", "_revivalStageInfoList"),
    ("way_point_data_list_deprecated", "_wayPointDataList_deprecated"),
];
