// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Each entry maps the Rust struct field name (snake_case, what shape='v3'
// emits today) to the canonical Pearl Abyss C++ identifier (with leading
// underscore, what shape='v3.1' emits). Mechanical transliteration:
// snake_case → prepend `_` + lowerCamelCase. v3 names are NEVER overwritten;
// these aliases just enable v3.1 consumers (DMM v2.0.0-beta etc.) to request
// the canonical names.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("knowledge_info", "_knowledgeInfo"),
    ("skill_tree_info", "_skillTreeInfo"),
    ("connect_research_node_info", "_connectResearchNodeInfo"),
    ("store_info", "_storeInfo"),
    ("royal_supply_info", "_royalSupplyInfo"),
    ("memo", "_memo"),
    ("child_faction_info_list", "_childFactionInfoList"),
    ("node_line_main_faction_info_list", "_nodeLineMainFactionInfoList"),
    ("world_position", "_worldPosition"),
    ("node_radius", "_nodeRadius"),
    ("apply_skill_data_list", "_applySkillDataList"),
    ("resource_item_list", "_resourceItemList"),
    ("revival_stage_info_list", "_revivalStageInfoList"),
    ("way_point_data_list_deprecated", "_wayPointDataListDeprecated"),
    ("faction_schedule_list", "_factionScheduleList"),
    ("unknown_a", "_unknownA"),
    ("key_str_after", "_keyStrAfter"),
    ("unknown_b", "_unknownB"),
    ("lookup_after", "_lookupAfter"),
    ("unknown_c", "_unknownC"),
    ("unknown_d", "_unknownD"),
    ("adjacency_list", "_adjacencyList"),
    ("big_composite_slots", "_bigCompositeSlots"),
    ("flag_after_slots", "_flagAfterSlots"),
    ("de690_data", "_de690Data"),
    ("raw_after_de690", "_rawAfterDe690"),
    ("final_list_u32", "_finalListU32"),
    ("final_list_u16", "_finalListU16"),
    ("final_lookup", "_finalLookup"),
];
