// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Mechanical translation only: this table is not present in NattKh's
// pabgb_complete_schema.json, so canonical names could not be
// independently verified. Aliases are derived from the Rust struct
// field name via snake → `_camelCase` conversion.
//
// v3 (snake_case) is the default emit; v3.1 emits the canonical `_camelCase`
// form. Round-trips identically — both names accepted on input.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("bank_step", "_bankStep"),
    ("bank_refresh_game_time_day", "_bankRefreshGameTimeDay"),
    ("bank_investment_item_info", "_bankInvestmentItemInfo"),
    ("exchange_item_data", "_exchangeItemData"),
    ("use_bank_condition", "_useBankCondition"),
    ("min_investment_amount", "_minInvestmentAmount"),
    ("max_amount_for_interest", "_maxAmountForInterest"),
    ("max_amount_for_interest_result", "_maxAmountForInterestResult"),
    ("bank_pass_item_info", "_bankPassItemInfo"),
    ("bank_license_knowledge_info", "_bankLicenseKnowledgeInfo"),
    ("fix_interest_rate_on_investment", "_fixInterestRateOnInvestment"),
    ("bank_interest_rate", "_bankInterestRate"),
];
