// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Each entry maps the Rust struct field name (snake_case, what shape='v3'
// emits today) to the canonical Pearl Abyss C++ identifier (with leading
// underscore, what shape='v3.1' emits). Mechanical transliteration:
// snake_case → prepend `_` + lowerCamelCase. v3 names are NEVER overwritten;
// these aliases just enable v3.1 consumers (DMM v2.0.0-beta etc.) to request
// the canonical names.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("skill_tree_info_list", "_skillTreeInfoList"),
    ("skill_group_name", "_skillGroupName"),
    ("skill_group_desc", "_skillGroupDesc"),
    ("ui_texture_icon_path", "_uiTextureIconPath"),
    ("character_info", "_characterInfo"),
    ("faction_node_info", "_factionNodeInfo"),
];
