// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Schema-verified: each canonical name was matched against
// NattKh/CrimsonDesertModdingTools `pabgb_complete_schema.json`
// (canonical PA identifiers extracted from Korean error strings
// in CrimsonDesert.exe). Only fields whose mechanical snake→camel
// translation matched a known canonical name were shipped.
//
// v3 (snake_case) is the default emit; v3.1 emits the canonical `_camelCase`
// form. Round-trips identically — both names accepted on input.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("exchange_item_info_for_buy", "_exchangeItemInfoForBuy"),
    ("exchange_item_info_list_for_sell", "_exchangeItemInfoListForSell"),
    ("sell_percents", "_sellPercents"),
    ("store_type", "_storeType"),
    ("price_increase_percent_list", "_priceIncreasePercentList"),
    ("sellable_character_condition_logic", "_sellableCharacterConditionLogic"),
    ("reset_hour", "_resetHour"),
    ("reset_day", "_resetDay"),
    ("buyable_stock_count", "_buyableStockCount"),
    ("sellable_stock_count", "_sellableStockCount"),
    ("sellable_type", "_sellableType"),
    ("stock_data_list", "_stockDataList"),
    ("sale_item_type_list", "_saleItemTypeList"),
    ("not_sale_item_type_list", "_notSaleItemTypeList"),
    ("custom_mesh_obb_max_length", "_customMeshOBBMaxLength"),
    ("fixed_price", "_fixedPrice"),
    ("use_housing_gimmick", "_useHousingGimmick"),
    ("reduce_price_by_looted_dead_body", "_reducePriceByLootedDeadBody"),
];
