// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Each entry maps the Rust struct field name (snake_case, what shape='v3'
// emits today) to the canonical Pearl Abyss C++ identifier (with leading
// underscore, what shape='v3.1' emits). Mechanical transliteration:
// snake_case → prepend `_` + lowerCamelCase. v3 names are NEVER overwritten;
// these aliases just enable v3.1 consumers (DMM v2.0.0-beta etc.) to request
// the canonical names.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("exchange_item_info_for_buy", "_exchangeItemInfoForBuy"),
    ("exchange_item_info_list_for_sell", "_exchangeItemInfoListForSell"),
    ("sell_percents", "_sellPercents"),
    ("store_type", "_storeType"),
    ("price_increase_percent_list", "_priceIncreasePercentList"),
    ("sellable_character_condition_logic", "_sellableCharacterConditionLogic"),
    ("reset_hour", "_resetHour"),
    ("reset_day", "_resetDay"),
    ("buyable_stock_count", "_buyableStockCount"),
    ("sellable_stock_count", "_sellableStockCount"),
    ("sellable_type", "_sellableType"),
    ("stock_data_list", "_stockDataList"),
    ("sale_item_type_list", "_saleItemTypeList"),
    ("not_sale_item_type_list", "_notSaleItemTypeList"),
    ("custom_mesh_obb_max_length", "_customMeshObbMaxLength"),
    ("fixed_price", "_fixedPrice"),
    ("use_housing_gimmick", "_useHousingGimmick"),
    ("reduce_price_by_looted_dead_body", "_reducePriceByLootedDeadBody"),
];
