// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Each entry maps the Rust struct field name (snake_case, what shape='v3'
// emits today) to the canonical Pearl Abyss C++ identifier (with leading
// underscore, what shape='v3.1' emits). Mechanical transliteration:
// snake_case → prepend `_` + lowerCamelCase. v3 names are NEVER overwritten;
// these aliases just enable v3.1 consumers (DMM v2.0.0-beta etc.) to request
// the canonical names.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("script_name", "_scriptName"),
    ("phase_panel_tag_name", "_phasePanelTagName"),
    ("ui_view_id", "_uiViewId"),
    ("use_deactive_result", "_useDeactiveResult"),
    ("need_change_character_scale", "_needChangeCharacterScale"),
    ("entrance_fee_list", "_entranceFeeList"),
    ("default_reward_drop_set_info", "_defaultRewardDropSetInfo"),
    ("player_data_list", "_playerDataList"),
    ("npc_data_list", "_npcDataList"),
    ("spawn_data_list", "_spawnDataList"),
    ("game_event_handler_info", "_gameEventHandlerInfo"),
    ("knowledge_info", "_knowledgeInfo"),
    ("game_advice_info_list", "_gameAdviceInfoList"),
];
