// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Schema-verified: each canonical name was matched against
// NattKh/CrimsonDesertModdingTools `pabgb_complete_schema.json`
// (canonical PA identifiers extracted from Korean error strings
// in CrimsonDesert.exe). Only fields whose mechanical snake→camel
// translation matched a known canonical name were shipped.
//
// v3 (snake_case) is the default emit; v3.1 emits the canonical `_camelCase`
// form. Round-trips identically — both names accepted on input.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("script_name", "_scriptName"),
    ("phase_panel_tag_name", "_phasePanelTagName"),
    ("ui_view_id", "_uiViewID"),
    ("use_deactive_result", "_useDeactiveResult"),
    ("need_change_character_scale", "_needChangeCharacterScale"),
    ("entrance_fee_list", "_entranceFeeList"),
    ("default_reward_drop_set_info", "_defaultRewardDropSetInfo"),
    ("player_data_list", "_playerDataList"),
    ("npc_data_list", "_npcDataList"),
    ("spawn_data_list", "_spawnDataList"),
    ("game_event_handler_info", "_gameEventHandlerInfo"),
    ("knowledge_info", "_knowledgeInfo"),
    ("game_advice_info_list", "_gameAdviceInfoList"),
];
