// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Schema-verified: each canonical name was matched against
// NattKh/CrimsonDesertModdingTools `pabgb_complete_schema.json`
// (canonical PA identifiers extracted from Korean error strings
// in CrimsonDesert.exe). Only fields whose mechanical snake→camel
// translation matched a known canonical name were shipped.
//
// v3 (snake_case) is the default emit; v3.1 emits the canonical `_camelCase`
// form. Round-trips identically — both names accepted on input.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("vehicle_type_name_hash", "_vehicleTypeNameHash"),
    ("icon_path", "_iconPath"),
    ("max_vehicle_seat", "_maxVehicleSeat"),
    ("max_parent_link_attach_count", "_maxParentLinkAttachCount"),
    ("rider_spawn_upper_action", "_riderSpawnUpperAction"),
    // `_riderSpawnLowerAction` REMOVED in game version 14 (2026-07-16) — see
    // vehicle_info/info.rs (confirmed absent in the 1.14 binary).
    ("vehicle_spawn_upper_action", "_vehicleSpawnUpperAction"),
    ("escape_road_group_type", "_escapeRoadGroupType"),
    ("cargo_seat_index_list", "_cargoSeatIndexList"),
    ("call_vehicle_voxel_type", "_callVehicleVoxelType"),
    ("is_main_dischargeable", "_isMainDischargeable"),
    ("show_count_on_ui", "_showCountOnUI"),
    ("ui_map_texture_info", "_uiMapTextureInfo"),
    ("send_damage_to", "_sendDamageTo"),
    ("character_switchable", "_characterSwitchable"),
    ("max_allowable_height", "_maxAllowableHeight"),
];
