// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Each entry maps the Rust struct field name (snake_case, what shape='v3'
// emits today) to the canonical Pearl Abyss C++ identifier (with leading
// underscore, what shape='v3.1' emits). Mechanical transliteration:
// snake_case → prepend `_` + lowerCamelCase. v3 names are NEVER overwritten;
// these aliases just enable v3.1 consumers (DMM v2.0.0-beta etc.) to request
// the canonical names.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("vehicle_type_name_hash", "_vehicleTypeNameHash"),
    ("icon_path", "_iconPath"),
    ("max_vehicle_seat", "_maxVehicleSeat"),
    ("vehicle_seat_data_00", "_vehicleSeatData00"),
    ("vehicle_seat_data_01", "_vehicleSeatData01"),
    ("vehicle_seat_data_02", "_vehicleSeatData02"),
    ("vehicle_seat_data_03", "_vehicleSeatData03"),
    ("vehicle_seat_data_04", "_vehicleSeatData04"),
    ("vehicle_seat_data_05", "_vehicleSeatData05"),
    ("vehicle_seat_data_06", "_vehicleSeatData06"),
    ("vehicle_seat_data_07", "_vehicleSeatData07"),
    ("vehicle_seat_data_08", "_vehicleSeatData08"),
    ("vehicle_seat_data_09", "_vehicleSeatData09"),
    ("vehicle_seat_data_10", "_vehicleSeatData10"),
    ("vehicle_seat_data_11", "_vehicleSeatData11"),
    ("vehicle_seat_data_12", "_vehicleSeatData12"),
    ("vehicle_seat_data_13", "_vehicleSeatData13"),
    ("vehicle_seat_data_14", "_vehicleSeatData14"),
    ("vehicle_seat_data_15", "_vehicleSeatData15"),
    ("max_parent_link_attach_count", "_maxParentLinkAttachCount"),
    ("parent_link_attach_data_a", "_parentLinkAttachDataA"),
    ("parent_link_attach_data_b", "_parentLinkAttachDataB"),
    ("rider_spawn_upper_action", "_riderSpawnUpperAction"),
    ("rider_spawn_lower_action", "_riderSpawnLowerAction"),
    ("vehicle_spawn_upper_action", "_vehicleSpawnUpperAction"),
    ("escape_road_group_type", "_escapeRoadGroupType"),
    ("cargo_seat_index_list", "_cargoSeatIndexList"),
    ("call_vehicle_voxel_type", "_callVehicleVoxelType"),
    ("is_main_dischargeable", "_isMainDischargeable"),
    ("show_count_on_ui", "_showCountOnUi"),
    ("ui_map_texture_info", "_uiMapTextureInfo"),
    ("rider_detect_info", "_riderDetectInfo"),
    ("send_damage_to", "_sendDamageTo"),
    ("character_switchable", "_characterSwitchable"),
    ("max_allowable_height", "_maxAllowableHeight"),
];
