// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Each entry maps the Rust struct field name (snake_case, what shape='v3'
// emits today) to the canonical Pearl Abyss C++ identifier (with leading
// underscore, what shape='v3.1' emits). Mechanical transliteration:
// snake_case → prepend `_` + lowerCamelCase. v3 names are NEVER overwritten;
// these aliases just enable v3.1 consumers (DMM v2.0.0-beta etc.) to request
// the canonical names.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("group_name", "_groupName"),
    ("character_info_list", "_characterInfoList"),
    ("group_gender_list", "_groupGenderList"),
    ("group_tribe_list", "_groupTribeList"),
    ("group_region_info_list", "_groupRegionInfoList"),
    ("group_age_list", "_groupAgeList"),
    ("group_weapon_type_list", "_groupWeaponTypeList"),
    ("group_tier_list", "_groupTierList"),
    ("group_ally_group_list", "_groupAllyGroupList"),
    ("group_faction_list", "_groupFactionList"),
    ("group_job_info_list", "_groupJobInfoList"),
    ("stop_anim_constraint_dead", "_stopAnimConstraintDead"),
];
