// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Schema-verified: each canonical name was matched against
// NattKh/CrimsonDesertModdingTools `pabgb_complete_schema.json`
// (canonical PA identifiers extracted from Korean error strings
// in CrimsonDesert.exe). Only fields whose mechanical snake→camel
// translation matched a known canonical name were shipped.
//
// v3 (snake_case) is the default emit; v3.1 emits the canonical `_camelCase`
// form. Round-trips identically — both names accepted on input.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("regenerate_type", "_regenerateType"),
    ("is_hard_coded", "_isHardCoded"),
    ("use_init_value_zero", "_useInitValueZero"),
    ("min_resistance_status_info", "_minResistanceStatusInfo"),
    ("max_resistance_status_info", "_maxResistanceStatusInfo"),
    ("is_resistance_stat", "_isResistanceStat"),
    ("is_elemental_stat", "_isElementalStat"),
    ("block_regen_on_min_stat_tick", "_blockRegenOnMinStatTick"),
    ("decrease_on_item_broken", "_decreaseOnItemBroken"),
    ("buff_info", "_buffInfo"),
    ("actual_status_key_to_refer", "_actualStatusKeyToRefer"),
    ("stat_type", "_statType"),
    ("static_stat_type", "_staticStatType"),
    ("elemental_stat_type", "_elementalStatType"),
    ("active_knowledge_info", "_activeKnowledgeInfo"),
    ("send_gimmick_event_key_for_stat_changed", "_sendGimmickEventKeyForStatChanged"),
    ("reserve_slot_info_list", "_reserveSlotInfoList"),
    ("use_limit_hit_min_stat", "_useLimitHitMinStat"),
    ("use_limit_hit_max_stat", "_useLimitHitMaxStat"),
    ("status_key_hash_code32", "_statusKeyHashCode32"),
    ("min_hash_code32", "_minHashCode32"),
    ("max_hash_code32", "_maxHashCode32"),
    ("is_full_recover_when_revived", "_isFullRecoverWhenRevived"),
    ("use_percent", "_usePercent"),
    ("is_repeat_update_from_server", "_isRepeatUpdateFromServer"),
    ("stat_level_data", "_statLevelData"),
    ("is_reset_on_revive", "_isResetOnRevive"),
    ("not_enough_resource_message", "_notEnoughResourceMessage"),
    ("ui_template_name", "_uiTemplateName"),
    ("ui_component_name", "_uiComponentName"),
];
