// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Schema-verified: each canonical name was matched against
// NattKh/CrimsonDesertModdingTools `pabgb_complete_schema.json`
// (canonical PA identifiers extracted from Korean error strings
// in CrimsonDesert.exe). Only fields whose mechanical snake→camel
// translation matched a known canonical name were shipped.
//
// v3 (snake_case) is the default emit; v3.1 emits the canonical `_camelCase`
// form. Round-trips identically — both names accepted on input.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("icon_path", "_iconPath"),
    ("store_info", "_storeInfo"),
    ("coupon_item_info", "_couponItemInfo"),
    ("npc_greet_friendly", "_npcGreetFriendly"),
    ("npc_function_type_flag", "_npcFunctionTypeFlag"),
    ("shop_scenekey", "_shopScenekey"),
    ("exchange_group_key", "_exchangeGroupKey"),
    ("exchange_button_text", "_exchangeButtonText"),
    ("shop_name", "_shopName"),
    ("interaction_name", "_interactionName"),
    ("dye_color_group_data_list", "_dyeColorGroupDataList"),
    ("dye_texture_set_data_list", "_dyeTextureSetDataList"),
];
