// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Each entry maps the Rust struct field name (snake_case, what shape='v3'
// emits today) to the canonical Pearl Abyss C++ identifier (with leading
// underscore, what shape='v3.1' emits). Mechanical transliteration:
// snake_case → prepend `_` + lowerCamelCase. v3 names are NEVER overwritten;
// these aliases just enable v3.1 consumers (DMM v2.0.0-beta etc.) to request
// the canonical names.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("icon_path", "_iconPath"),
    ("store_info", "_storeInfo"),
    ("coupon_item_info", "_couponItemInfo"),
    ("npc_greet_friendly", "_npcGreetFriendly"),
    ("npc_function_type_flag", "_npcFunctionTypeFlag"),
    ("shop_scenekey", "_shopScenekey"),
    ("exchange_group_key", "_exchangeGroupKey"),
    ("exchange_button_text", "_exchangeButtonText"),
    ("shop_name", "_shopName"),
    ("interaction_name", "_interactionName"),
    ("dye_color_group_data_list", "_dyeColorGroupDataList"),
    ("dye_texture_set_data_list", "_dyeTextureSetDataList"),
];
