// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Schema-verified: each canonical name was matched against
// NattKh/CrimsonDesertModdingTools `pabgb_complete_schema.json`
// (canonical PA identifiers extracted from Korean error strings
// in CrimsonDesert.exe). Only fields whose mechanical snake→camel
// translation matched a known canonical name were shipped.
//
// v3 (snake_case) is the default emit; v3.1 emits the canonical `_camelCase`
// form. Round-trips identically — both names accepted on input.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("knowledge_group_name", "_knowledgeGroupName"),
    ("knowledge_group_unknown_name", "_knowledgeGroupUnknownName"),
    ("knowledge_group_desc", "_knowledgeGroupDesc"),
    ("ui_texture_name", "_uiTextureName"),
    ("knowledge_group_icon_path", "_knowledgeGroupIconPath"),
    ("ui_component_name", "_uiComponentName"),
    ("knowledge_info_list", "_knowledgeInfoList"),
    ("child_knowledge_group_info_list", "_childKnowledgeGroupInfoList"),
    ("parent_knowledge_group_info", "_parentKnowledgeGroupInfo"),
    ("is_meditation_learnable", "_isMeditationLearnable"),
];
