// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Schema-verified: each canonical name was matched against
// NattKh/CrimsonDesertModdingTools `pabgb_complete_schema.json`
// (canonical PA identifiers extracted from Korean error strings
// in CrimsonDesert.exe). Only fields whose mechanical snake→camel
// translation matched a known canonical name were shipped.
//
// v3 (snake_case) is the default emit; v3.1 emits the canonical `_camelCase`
// form. Round-trips identically — both names accepted on input.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("memo", "_memo"),
    ("category_type", "_categoryType"),
    ("flag_component_name", "_flagComponentName"),
    ("knowledge_info", "_knowledgeInfo"),
    ("contribution_sub_level_info", "_contributionSubLevelInfo"),
    ("contribution_worker_info", "_contributionWorkerInfo"),
    ("trade_reward_dropset_info", "_tradeRewardDropsetInfo"),
    ("faction_relation_group_info", "_factionRelationGroupInfo"),
    ("faction_group_info", "_factionGroupInfo"),
    ("represent_faction_info", "_representFactionInfo"),
    ("stage_icon_path", "_stageIconPath"),
    ("faction_ui_card_list", "_factionUiCardList"),
    ("stealth_option_list", "_stealthOptionList"),
    ("faction_event_data_list", "_factionEventDataList"),
    ("is_empty_misc", "_isEmptyMisc"),
    ("faction_color", "_factionColor"),
];
