// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Each entry maps the Rust struct field name (snake_case, what shape='v3'
// emits today) to the canonical Pearl Abyss C++ identifier (with leading
// underscore, what shape='v3.1' emits). Mechanical transliteration:
// snake_case → prepend `_` + lowerCamelCase. v3 names are NEVER overwritten;
// these aliases just enable v3.1 consumers (DMM v2.0.0-beta etc.) to request
// the canonical names.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("memo", "_memo"),
    ("category_type", "_categoryType"),
    ("flag_component_name", "_flagComponentName"),
    ("knowledge_info", "_knowledgeInfo"),
    ("contribution_sub_level_info", "_contributionSubLevelInfo"),
    ("contribution_worker_info", "_contributionWorkerInfo"),
    ("trade_reward_dropset_info", "_tradeRewardDropsetInfo"),
    ("faction_relation_group_info", "_factionRelationGroupInfo"),
    ("faction_group_info", "_factionGroupInfo"),
    ("represent_faction_info_lookup_a", "_representFactionInfoLookupA"),
    ("represent_faction_info_lookup_b", "_representFactionInfoLookupB"),
    ("represent_faction_info", "_representFactionInfo"),
    ("stage_icon_path", "_stageIconPath"),
    ("faction_ui_card_list", "_factionUiCardList"),
    ("stealth_option_list", "_stealthOptionList"),
    ("faction_event_data_list", "_factionEventDataList"),
    ("is_empty_misc", "_isEmptyMisc"),
    ("faction_color", "_factionColor"),
    ("unk_new_u32", "_unkNewU32"),
];
