// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Each entry maps the Rust struct field name (snake_case, what shape='v3'
// emits today) to the canonical Pearl Abyss C++ identifier (with leading
// underscore, what shape='v3.1' emits). Mechanical transliteration:
// snake_case → prepend `_` + lowerCamelCase. v3 names are NEVER overwritten;
// these aliases just enable v3.1 consumers (DMM v2.0.0-beta etc.) to request
// the canonical names.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("pushable_item_type_list", "_pushableItemTypeList"),
    ("excluded_item_type_list", "_excludedItemTypeList"),
    ("inventory_move_data_list", "_inventoryMoveDataList"),
    ("default_slot_count", "_defaultSlotCount"),
    ("max_slot_count", "_maxSlotCount"),
    ("push_item_alert_ui_text", "_pushItemAlertUiText"),
    ("inventory_name_ui_text", "_inventoryNameUiText"),
    ("key_guide_local_string_info", "_keyGuideLocalStringInfo"),
    ("pushable_check_type", "_pushableCheckType"),
    ("npc_usable_cooltime_min", "_npcUsableCooltimeMin"),
    ("npc_usable_cooltime_max", "_npcUsableCooltimeMax"),
    ("is_moveable_inventory", "_isMoveableInventory"),
    ("need_save_slot_count", "_needSaveSlotCount"),
    ("is_pushable_item_only_one", "_isPushableItemOnlyOne"),
    ("collection_item_list", "_collectionItemList"),
];
