// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Each entry maps the Rust struct field name (snake_case, what shape='v3'
// emits today) to the canonical Pearl Abyss C++ identifier (with leading
// underscore, what shape='v3.1' emits). Mechanical transliteration:
// snake_case → prepend `_` + lowerCamelCase. v3 names are NEVER overwritten;
// these aliases just enable v3.1 consumers (DMM v2.0.0-beta etc.) to request
// the canonical names.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("scale_type", "_scaleType"),
    ("values", "_values"),
    ("boundary_position_min", "_boundaryPositionMin"),
    ("boundary_position_max", "_boundaryPositionMax"),
    ("center_position", "_centerPosition"),
    ("scale_per_pixel", "_scalePerPixel"),
    ("max_using_height", "_maxUsingHeight"),
    ("export_texture_on_editing", "_exportTextureOnEditing"),
];
