// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Schema-verified: each canonical name was matched against
// NattKh/CrimsonDesertModdingTools `pabgb_complete_schema.json`
// (canonical PA identifiers extracted from Korean error strings
// in CrimsonDesert.exe). Only fields whose mechanical snake→camel
// translation matched a known canonical name were shipped.
//
// v3 (snake_case) is the default emit; v3.1 emits the canonical `_camelCase`
// form. Round-trips identically — both names accepted on input.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("main_gimmick_group_info_of_combination", "_mainGimmickGroupInfoOfCombination"),
    ("battery_init_capacity", "_batteryInitCapacity"),
    ("battery_total_capacity", "_batteryTotalCapacity"),
    ("link_signal_group_list", "_linkSignalGroupList"),
    ("property_list", "_propertyList"),
    ("gimmick_tag_list", "_gimmickTagList"),
    ("gimmick_chart_path", "_gimmickChartPath"),
    ("gimmick_type", "_gimmickType"),
    ("gimmick_placement_style", "_gimmickPlacementStyle"),
    ("gimmick_interface_type", "_gimmickInterfaceType"),
    ("gimmick_remote_catchable_data", "_gimmickRemoteCatchableData"),
    ("auto_targeting_constraint_data_list", "_autoTargetingConstraintDataList"),
    ("gimmick_constraint_data_list", "_gimmickConstraintDataList"),
    ("gimmick_info_list", "_gimmickInfoList"),
    ("game_event_handler_list", "_gameEventHandlerList"),
    ("default_spawn_reason_hash", "_defaultSpawnReasonHash"),
    ("initial_body_motion_type", "_initialBodyMotionType"),
    ("sequencer_level_allow_gimmick_event_key_list", "_sequencerLevelAllowGimmickEventKeyList"),
    ("sequencer_level_connect_alias_name_list", "_sequencerLevelConnectAliasNameList"),
    ("gimmick_alias_data_list", "_gimmickAliasDataList"),
    ("logout_time_after_break", "_logoutTimeAfterBreak"),
    ("attack_by_collision_info_list_key", "_attackByCollisionInfoListKey"),
    ("raw_340", "_spawnDistanceLevel"),
];
