// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Schema-verified: each canonical name was matched against
// NattKh/CrimsonDesertModdingTools `pabgb_complete_schema.json`
// (canonical PA identifiers extracted from Korean error strings
// in CrimsonDesert.exe). Only fields whose mechanical snake→camel
// translation matched a known canonical name were shipped.
//
// v3 (snake_case) is the default emit; v3.1 emits the canonical `_camelCase`
// form. Round-trips identically — both names accepted on input.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("ui_icon_path", "_uiIconPath"),
    ("category", "_category"),
    ("character_edit_name", "_characterEditName"),
    ("spawn_actor_type", "_spawnActorType"),
    ("none_player_sub_type", "_nonePlayerSubType"),
    ("equip_info", "_equipInfo"),
    ("npc_info", "_npcInfo"),
    ("vehicle_info", "_vehicleInfo"),
    ("call_mercenary_cool_time", "_callMercenaryCoolTime"),
    ("call_mercenary_spawn_duration", "_callMercenarySpawnDuration"),
    ("mercenary_cool_time_type", "_mercenaryCoolTimeType"),
    ("character_game_play_data_name", "_characterGamePlayDataName"),
    ("appearance_name", "_appearanceName"),
    ("character_prefab_path", "_characterPrefabPath"),
    ("skeleton_name", "_skeletonName"),
    ("lookup_24", "_lookup24"),
    ("lookup_25", "_lookup25"),
    ("flag_c", "_flagC"),
];
