// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Each entry maps the Rust struct field name (snake_case, what shape='v3'
// emits today) to the canonical Pearl Abyss C++ identifier (with leading
// underscore, what shape='v3.1' emits). Mechanical transliteration:
// snake_case → prepend `_` + lowerCamelCase. v3 names are NEVER overwritten;
// these aliases just enable v3.1 consumers (DMM v2.0.0-beta etc.) to request
// the canonical names.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("reaction_row_0", "_reactionRow0"),
    ("reaction_row_1", "_reactionRow1"),
    ("reaction_row_2", "_reactionRow2"),
    ("reaction_row_3", "_reactionRow3"),
    ("reaction_row_4", "_reactionRow4"),
    ("buff_reaction_type", "_buffReactionType"),
    ("strong_buff_reaction_type", "_strongBuffReactionType"),
    ("player_sensible_reaction_type", "_playerSensibleReactionType"),
];
