// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Schema-verified: each canonical name was matched against
// NattKh/CrimsonDesertModdingTools `pabgb_complete_schema.json`
// (canonical PA identifiers extracted from Korean error strings
// in CrimsonDesert.exe). Only fields whose mechanical snake→camel
// translation matched a known canonical name were shipped.
//
// v3 (snake_case) is the default emit; v3.1 emits the canonical `_camelCase`
// form. Round-trips identically — both names accepted on input.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("buff_reaction_type", "_buffReactionType"),
    ("strong_buff_reaction_type", "_strongBuffReactionType"),
    ("player_sensible_reaction_type", "_playerSensibleReactionType"),
];
