// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Each entry maps the Rust struct field name (snake_case, what shape='v3'
// emits today) to the canonical Pearl Abyss C++ identifier (with leading
// underscore, what shape='v3.1' emits). Mechanical transliteration:
// snake_case → prepend `_` + lowerCamelCase. v3 names are NEVER overwritten;
// these aliases just enable v3.1 consumers (DMM v2.0.0-beta etc.) to request
// the canonical names.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("group_name", "_groupName"),
    ("item_group_info_list", "_itemGroupInfoList"),
    ("item_info_list", "_itemInfoList"),
    ("category_type_list", "_categoryTypeList"),
    ("order_index", "_orderIndex"),
    ("item_cage_type", "_itemCageType"),
    ("icon_path", "_iconPath"),
    ("is_show_category_string", "_isShowCategoryString"),
    ("is_group_item_lockable", "_isGroupItemLockable"),
    ("is_monster_only_equip", "_isMonsterOnlyEquip"),
    ("is_always_fold_item_group", "_isAlwaysFoldItemGroup"),
];
