// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Each entry maps the Rust struct field name (snake_case, what shape='v3'
// emits today) to the canonical Pearl Abyss C++ identifier (with leading
// underscore, what shape='v3.1' emits). Mechanical transliteration:
// snake_case → prepend `_` + lowerCamelCase. v3 names are NEVER overwritten;
// these aliases just enable v3.1 consumers (DMM v2.0.0-beta etc.) to request
// the canonical names.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("relation_type_list_0", "_relationTypeList0"),
    ("relation_type_list_1", "_relationTypeList1"),
    ("relation_type_list_2", "_relationTypeList2"),
    ("relation_type_list_3", "_relationTypeList3"),
    ("relation_type_list_4", "_relationTypeList4"),
    ("relation_type_list_5", "_relationTypeList5"),
    ("relation_type_list_6", "_relationTypeList6"),
    ("killer_detection_time", "_killerDetectionTime"),
    ("apply_reporting", "_applyReporting"),
    ("is_wild", "_isWild"),
    ("is_main_ally_group", "_isMainAllyGroup"),
    ("is_intruder", "_isIntruder"),
    ("interesting_condition", "_interestingCondition"),
    ("add_on_ally_group_list", "_addOnAllyGroupList"),
    ("interesting_order_list", "_interestingOrderList"),
];
