// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Schema-verified: each canonical name was matched against
// NattKh/CrimsonDesertModdingTools `pabgb_complete_schema.json`
// (canonical PA identifiers extracted from Korean error strings
// in CrimsonDesert.exe). Only fields whose mechanical snake→camel
// translation matched a known canonical name were shipped.
//
// v3 (snake_case) is the default emit; v3.1 emits the canonical `_camelCase`
// form. Round-trips identically — both names accepted on input.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("character_info", "_characterInfo"),
    ("faction_info", "_factionInfo"),
    ("item_info", "_itemInfo"),
    ("ui_grid_size_x", "_uiGridSizeX"),
    ("ui_grid_size_y", "_uiGridSizeY"),
    ("ui_texture_icon_path", "_uiTextureIconPath"),
    ("ui_page_name", "_uiPageName"),
    ("skill_node_list", "_skillNodeList"),
    ("stat_node_list", "_statNodeList"),
    ("first_focus_skill_info", "_firstFocusSkillInfo"),
    ("first_focus_zoom", "_firstFocusZoom"),
    ("first_focus_position", "_firstFocusPosition"),
];
