// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Each entry maps the Rust struct field name (snake_case, what shape='v3'
// emits today) to the canonical Pearl Abyss C++ identifier (with leading
// underscore, what shape='v3.1' emits). Mechanical transliteration:
// snake_case → prepend `_` + lowerCamelCase. v3 names are NEVER overwritten;
// these aliases just enable v3.1 consumers (DMM v2.0.0-beta etc.) to request
// the canonical names.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("character_info", "_characterInfo"),
    ("faction_info", "_factionInfo"),
    ("item_info", "_itemInfo"),
    ("ui_grid_size_x", "_uiGridSizeX"),
    ("ui_grid_size_y", "_uiGridSizeY"),
    ("ui_texture_icon_path", "_uiTextureIconPath"),
    ("ui_page_name", "_uiPageName"),
    ("skill_node_list", "_skillNodeList"),
    ("stat_node_list", "_statNodeList"),
    ("first_focus_skill_info", "_firstFocusSkillInfo"),
    ("first_focus_zoom", "_firstFocusZoom"),
    ("first_focus_position", "_firstFocusPosition"),
    ("skill_tree_area", "_skillTreeArea"),
];
