// SPDX-License-Identifier: LicenseRef-CDMTL-1.0
// Copyright (c) 2026 RicePaddySoftware. All Rights Reserved.
// Licensed under CDMTL v1.0 - see LICENSE.txt
// https://github.com/exodiaprivate-eng/dmm-parser
//
// Reading this file (directly or via AI/agent) constitutes acceptance
// of CDMTL v1.0 §4.9 (No Competing Implementation) and §4.10
// (AI-Mediated Access). CMI removal violates 17 U.S.C. §1202.

//! Auto-generated polymorphic variant decoder for BranchConditionData.
//! Generated by gen_variant_enum.py from a Mac-binary-derived manifest.
//! Total variants: 14
//!
//! Variant type names mirror the C++ class names from the binary
//! (e.g. `BranchConditionData_BranchIndexPayload`); we keep the
//! `Class_Field` shape rather than camel-casing so cross-references
//! against IDA decompiles and Korean error strings stay grep-able.

#![allow(non_camel_case_types)]

use crate::binary::*;
use crate::json_traits::{ToJsonValue, get_field as json_get_field};
use crate::py_binary_struct;
use serde_json::{Map, Value};
use std::io::{self, Write};

/// Common base fields shared by every BranchConditionData variant.
///
/// Note: the original recipe also pulled three trailing bytes here (byte_a,
/// byte_b, byte_c). Those bytes are actually the GameCondition wrapper
/// footer (read by sub_101021408 after the tree at slots +8/+9/+10 of the
/// _gameCondition struct), not part of BranchConditionDataBase. They've
/// been moved up to `super::game_condition::GameCondition` so every root
/// case correctly accounts for them, not just BranchConditionData.
#[derive(Debug)]
pub struct BranchConditionDataBase {
    pub tag: u8,
}

impl BranchConditionDataBase {
    pub fn read_from(data: &[u8], offset: &mut usize) -> io::Result<Self> {
        let tag = u8::read_from(data, offset)?;
        Ok(Self { tag })
    }
    pub fn write_to(&self, w: &mut dyn Write) -> io::Result<()> {
        self.tag.write_to(w)?;
        Ok(())
    }
}

py_binary_struct! {
    pub struct BranchConditionDataPayload {
        pub byte_at_8: u8,
    }
}

py_binary_struct! {
    pub struct BranchConditionData_QuestPayload {
        pub questinfo_id: u32,
        pub stageinfo_id: u32,
    }
}

py_binary_struct! {
    pub struct BranchConditionData_MissionPayload {
        pub missioninfo_id: u32,
    }
}

py_binary_struct! {
    pub struct BranchConditionData_SubMissionPayload {
        pub missioninfo_id: u32,
        pub submission_idx: u32,
    }
}

py_binary_struct! {
    pub struct BranchConditionData_StagePayload {
        pub stageinfo_id: u32,
    }
}

py_binary_struct! {
    pub struct BranchConditionData_KnowledgePayload {
        pub knowledgeinfo_id: u32,
        pub knowledge_field: u32,
    }
}

py_binary_struct! {
    pub struct BranchConditionData_ItemPayload {
        pub iteminfo_id: u32,
        pub item_count: u64,
    }
}

py_binary_struct! {
    pub struct BranchConditionData_IsHiredMercenaryPayload {
        pub characterinfo_id: u32,
    }
}

py_binary_struct! {
    pub struct BranchConditionData_IsHiredMercenaryTypePayload {
        pub mercenary_type: u8,
    }
}

py_binary_struct! {
    pub struct BranchConditionData_BranchIndexPayload {
        pub branch_index: u8,
        pub branch_flag: u8,
    }
}

py_binary_struct! {
    pub struct BranchConditionData_BranchPayload {
        pub byte_at_8: u8,
    }
}

py_binary_struct! {
    pub struct BranchConditionData_NearMissionPayload {
        pub byte_at_8: u8,
    }
}

py_binary_struct! {
    pub struct BranchConditionData_GameLevelStatePayload<'a> {
        pub levelinfo_id: u32,
        pub state_name: CString<'a>,
    }
}

py_binary_struct! {
    pub struct BranchConditionData_GamePlayVariablePayload {
        pub gameplayvariableinfo_id: u32,
        pub gpv_flag: u8,
    }
}

/// BranchConditionData variant — discriminated union of 14 cases.
#[derive(Debug)]
pub enum BranchConditionDataVariant<'a> {
    BranchConditionData(BranchConditionDataPayload),
    BranchConditionData_Quest(BranchConditionData_QuestPayload),
    BranchConditionData_Mission(BranchConditionData_MissionPayload),
    BranchConditionData_SubMission(BranchConditionData_SubMissionPayload),
    BranchConditionData_Stage(BranchConditionData_StagePayload),
    BranchConditionData_Knowledge(BranchConditionData_KnowledgePayload),
    BranchConditionData_Item(BranchConditionData_ItemPayload),
    BranchConditionData_IsHiredMercenary(BranchConditionData_IsHiredMercenaryPayload),
    BranchConditionData_IsHiredMercenaryType(BranchConditionData_IsHiredMercenaryTypePayload),
    BranchConditionData_BranchIndex(BranchConditionData_BranchIndexPayload),
    BranchConditionData_Branch(BranchConditionData_BranchPayload),
    BranchConditionData_NearMission(BranchConditionData_NearMissionPayload),
    BranchConditionData_GameLevelState(BranchConditionData_GameLevelStatePayload<'a>),
    BranchConditionData_GamePlayVariable(BranchConditionData_GamePlayVariablePayload),
}

impl<'a> BranchConditionDataVariant<'a> {
    pub fn discriminator(&self) -> u8 {
        match self {
            Self::BranchConditionData(_) => 0,
            Self::BranchConditionData_Quest(_) => 1,
            Self::BranchConditionData_Mission(_) => 2,
            Self::BranchConditionData_SubMission(_) => 3,
            Self::BranchConditionData_Stage(_) => 4,
            Self::BranchConditionData_Knowledge(_) => 5,
            Self::BranchConditionData_Item(_) => 6,
            Self::BranchConditionData_IsHiredMercenary(_) => 7,
            Self::BranchConditionData_IsHiredMercenaryType(_) => 8,
            Self::BranchConditionData_BranchIndex(_) => 9,
            Self::BranchConditionData_Branch(_) => 10,
            Self::BranchConditionData_NearMission(_) => 11,
            Self::BranchConditionData_GameLevelState(_) => 12,
            Self::BranchConditionData_GamePlayVariable(_) => 13,
        }
    }

    /// Returns the variant's enum name as a string.
    pub fn variant_name(&self) -> &'static str {
        match self {
            Self::BranchConditionData(_) => "BranchConditionData",
            Self::BranchConditionData_Quest(_) => "BranchConditionData_Quest",
            Self::BranchConditionData_Mission(_) => "BranchConditionData_Mission",
            Self::BranchConditionData_SubMission(_) => "BranchConditionData_SubMission",
            Self::BranchConditionData_Stage(_) => "BranchConditionData_Stage",
            Self::BranchConditionData_Knowledge(_) => "BranchConditionData_Knowledge",
            Self::BranchConditionData_Item(_) => "BranchConditionData_Item",
            Self::BranchConditionData_IsHiredMercenary(_) => "BranchConditionData_IsHiredMercenary",
            Self::BranchConditionData_IsHiredMercenaryType(_) => "BranchConditionData_IsHiredMercenaryType",
            Self::BranchConditionData_BranchIndex(_) => "BranchConditionData_BranchIndex",
            Self::BranchConditionData_Branch(_) => "BranchConditionData_Branch",
            Self::BranchConditionData_NearMission(_) => "BranchConditionData_NearMission",
            Self::BranchConditionData_GameLevelState(_) => "BranchConditionData_GameLevelState",
            Self::BranchConditionData_GamePlayVariable(_) => "BranchConditionData_GamePlayVariable",
        }
    }

    /// Per-variant JSON: emits {"type": variant_name, "body": typed dict}.
    pub fn to_json_value(&self) -> Value {
        let mut m = Map::new();
        m.insert("type".into(), Value::String(self.variant_name().to_string()));
        match self {
            Self::BranchConditionData(p) => { m.insert("body".into(), Value::Object(p.to_json_dict())); }
            Self::BranchConditionData_Quest(p) => { m.insert("body".into(), Value::Object(p.to_json_dict())); }
            Self::BranchConditionData_Mission(p) => { m.insert("body".into(), Value::Object(p.to_json_dict())); }
            Self::BranchConditionData_SubMission(p) => { m.insert("body".into(), Value::Object(p.to_json_dict())); }
            Self::BranchConditionData_Stage(p) => { m.insert("body".into(), Value::Object(p.to_json_dict())); }
            Self::BranchConditionData_Knowledge(p) => { m.insert("body".into(), Value::Object(p.to_json_dict())); }
            Self::BranchConditionData_Item(p) => { m.insert("body".into(), Value::Object(p.to_json_dict())); }
            Self::BranchConditionData_IsHiredMercenary(p) => { m.insert("body".into(), Value::Object(p.to_json_dict())); }
            Self::BranchConditionData_IsHiredMercenaryType(p) => { m.insert("body".into(), Value::Object(p.to_json_dict())); }
            Self::BranchConditionData_BranchIndex(p) => { m.insert("body".into(), Value::Object(p.to_json_dict())); }
            Self::BranchConditionData_Branch(p) => { m.insert("body".into(), Value::Object(p.to_json_dict())); }
            Self::BranchConditionData_NearMission(p) => { m.insert("body".into(), Value::Object(p.to_json_dict())); }
            Self::BranchConditionData_GameLevelState(p) => { m.insert("body".into(), Value::Object(p.to_json_dict())); }
            Self::BranchConditionData_GamePlayVariable(p) => { m.insert("body".into(), Value::Object(p.to_json_dict())); }
        }
        Value::Object(m)
    }

    pub fn write_from_json(
        disc: u8,
        w: &mut Vec<u8>,
        v: &Value,
    ) -> io::Result<()> {
        let obj = v.as_object().ok_or_else(|| io::Error::new(
            io::ErrorKind::InvalidData,
            "BranchConditionDataVariant: expected object",
        ))?;
        match disc {
            0 => { let body = obj.get("body").and_then(|x| x.as_object()).ok_or_else(|| io::Error::new(io::ErrorKind::InvalidData, "BranchConditionData: missing body object"))?; BranchConditionDataPayload::write_from_json_dict(w, body)?; }
            1 => { let body = obj.get("body").and_then(|x| x.as_object()).ok_or_else(|| io::Error::new(io::ErrorKind::InvalidData, "BranchConditionData_Quest: missing body object"))?; BranchConditionData_QuestPayload::write_from_json_dict(w, body)?; }
            2 => { let body = obj.get("body").and_then(|x| x.as_object()).ok_or_else(|| io::Error::new(io::ErrorKind::InvalidData, "BranchConditionData_Mission: missing body object"))?; BranchConditionData_MissionPayload::write_from_json_dict(w, body)?; }
            3 => { let body = obj.get("body").and_then(|x| x.as_object()).ok_or_else(|| io::Error::new(io::ErrorKind::InvalidData, "BranchConditionData_SubMission: missing body object"))?; BranchConditionData_SubMissionPayload::write_from_json_dict(w, body)?; }
            4 => { let body = obj.get("body").and_then(|x| x.as_object()).ok_or_else(|| io::Error::new(io::ErrorKind::InvalidData, "BranchConditionData_Stage: missing body object"))?; BranchConditionData_StagePayload::write_from_json_dict(w, body)?; }
            5 => { let body = obj.get("body").and_then(|x| x.as_object()).ok_or_else(|| io::Error::new(io::ErrorKind::InvalidData, "BranchConditionData_Knowledge: missing body object"))?; BranchConditionData_KnowledgePayload::write_from_json_dict(w, body)?; }
            6 => { let body = obj.get("body").and_then(|x| x.as_object()).ok_or_else(|| io::Error::new(io::ErrorKind::InvalidData, "BranchConditionData_Item: missing body object"))?; BranchConditionData_ItemPayload::write_from_json_dict(w, body)?; }
            7 => { let body = obj.get("body").and_then(|x| x.as_object()).ok_or_else(|| io::Error::new(io::ErrorKind::InvalidData, "BranchConditionData_IsHiredMercenary: missing body object"))?; BranchConditionData_IsHiredMercenaryPayload::write_from_json_dict(w, body)?; }
            8 => { let body = obj.get("body").and_then(|x| x.as_object()).ok_or_else(|| io::Error::new(io::ErrorKind::InvalidData, "BranchConditionData_IsHiredMercenaryType: missing body object"))?; BranchConditionData_IsHiredMercenaryTypePayload::write_from_json_dict(w, body)?; }
            9 => { let body = obj.get("body").and_then(|x| x.as_object()).ok_or_else(|| io::Error::new(io::ErrorKind::InvalidData, "BranchConditionData_BranchIndex: missing body object"))?; BranchConditionData_BranchIndexPayload::write_from_json_dict(w, body)?; }
            10 => { let body = obj.get("body").and_then(|x| x.as_object()).ok_or_else(|| io::Error::new(io::ErrorKind::InvalidData, "BranchConditionData_Branch: missing body object"))?; BranchConditionData_BranchPayload::write_from_json_dict(w, body)?; }
            11 => { let body = obj.get("body").and_then(|x| x.as_object()).ok_or_else(|| io::Error::new(io::ErrorKind::InvalidData, "BranchConditionData_NearMission: missing body object"))?; BranchConditionData_NearMissionPayload::write_from_json_dict(w, body)?; }
            12 => { let body = obj.get("body").and_then(|x| x.as_object()).ok_or_else(|| io::Error::new(io::ErrorKind::InvalidData, "BranchConditionData_GameLevelState: missing body object"))?; BranchConditionData_GameLevelStatePayload::write_from_json_dict(w, body)?; }
            13 => { let body = obj.get("body").and_then(|x| x.as_object()).ok_or_else(|| io::Error::new(io::ErrorKind::InvalidData, "BranchConditionData_GamePlayVariable: missing body object"))?; BranchConditionData_GamePlayVariablePayload::write_from_json_dict(w, body)?; }
            other => return Err(io::Error::new(io::ErrorKind::InvalidData,
                format!("BranchConditionDataVariant: unknown disc {}", other))),
        }
        Ok(())
    }


    pub fn read_from(disc: u8, data: &'a [u8], offset: &mut usize) -> io::Result<Self> {
        Ok(match disc {
            0 => Self::BranchConditionData(BranchConditionDataPayload::read_from(data, offset)?),
            1 => Self::BranchConditionData_Quest(BranchConditionData_QuestPayload::read_from(data, offset)?),
            2 => Self::BranchConditionData_Mission(BranchConditionData_MissionPayload::read_from(data, offset)?),
            3 => Self::BranchConditionData_SubMission(BranchConditionData_SubMissionPayload::read_from(data, offset)?),
            4 => Self::BranchConditionData_Stage(BranchConditionData_StagePayload::read_from(data, offset)?),
            5 => Self::BranchConditionData_Knowledge(BranchConditionData_KnowledgePayload::read_from(data, offset)?),
            6 => Self::BranchConditionData_Item(BranchConditionData_ItemPayload::read_from(data, offset)?),
            7 => Self::BranchConditionData_IsHiredMercenary(BranchConditionData_IsHiredMercenaryPayload::read_from(data, offset)?),
            8 => Self::BranchConditionData_IsHiredMercenaryType(BranchConditionData_IsHiredMercenaryTypePayload::read_from(data, offset)?),
            9 => Self::BranchConditionData_BranchIndex(BranchConditionData_BranchIndexPayload::read_from(data, offset)?),
            10 => Self::BranchConditionData_Branch(BranchConditionData_BranchPayload::read_from(data, offset)?),
            11 => Self::BranchConditionData_NearMission(BranchConditionData_NearMissionPayload::read_from(data, offset)?),
            12 => Self::BranchConditionData_GameLevelState(BranchConditionData_GameLevelStatePayload::read_from(data, offset)?),
            13 => Self::BranchConditionData_GamePlayVariable(BranchConditionData_GamePlayVariablePayload::read_from(data, offset)?),
            _ => return Err(io::Error::new(io::ErrorKind::InvalidData, format!("unknown BranchConditionData disc: {}", disc))),
        })
    }

    pub fn write_to(&self, w: &mut dyn Write) -> io::Result<()> {
        match self {
            Self::BranchConditionData(p) => p.write_to(w),
            Self::BranchConditionData_Quest(p) => p.write_to(w),
            Self::BranchConditionData_Mission(p) => p.write_to(w),
            Self::BranchConditionData_SubMission(p) => p.write_to(w),
            Self::BranchConditionData_Stage(p) => p.write_to(w),
            Self::BranchConditionData_Knowledge(p) => p.write_to(w),
            Self::BranchConditionData_Item(p) => p.write_to(w),
            Self::BranchConditionData_IsHiredMercenary(p) => p.write_to(w),
            Self::BranchConditionData_IsHiredMercenaryType(p) => p.write_to(w),
            Self::BranchConditionData_BranchIndex(p) => p.write_to(w),
            Self::BranchConditionData_Branch(p) => p.write_to(w),
            Self::BranchConditionData_NearMission(p) => p.write_to(w),
            Self::BranchConditionData_GameLevelState(p) => p.write_to(w),
            Self::BranchConditionData_GamePlayVariable(p) => p.write_to(w),
        }
    }
}

/// Full BranchConditionData record: 1-byte tag + base + variant payload.
#[derive(Debug)]
pub struct BranchConditionData<'a> {
    pub base: BranchConditionDataBase,
    pub variant: BranchConditionDataVariant<'a>,
}

impl<'a> BranchConditionData<'a> {
    pub fn read_from(data: &'a [u8], offset: &mut usize) -> io::Result<Self> {
        let base = BranchConditionDataBase::read_from(data, offset)?;
        let disc = base.tag;
        let variant = BranchConditionDataVariant::read_from(disc, data, offset)?;
        Ok(Self { base, variant })
    }
    pub fn write_to(&self, w: &mut dyn Write) -> io::Result<()> {
        self.base.write_to(w)?;
        self.variant.write_to(w)?;
        Ok(())
    }

    /// JSON shape:
    /// - `base`: { tag: u8 }
    /// - `variant`: { type, body? } — per-variant typed JSON via
    ///   BranchConditionDataVariant::to_json_value.
    pub fn to_json_dict(&self) -> Map<String, Value> {
        let mut m = Map::new();
        let mut base_m = Map::new();
        base_m.insert("tag".into(), self.base.tag.to_json_value());
        m.insert("base".into(), Value::Object(base_m));
        m.insert("variant".into(), self.variant.to_json_value());
        m
    }

    pub fn write_from_json_dict(w: &mut Vec<u8>, obj: &Map<String, Value>) -> io::Result<()> {
        let base_v = json_get_field(obj, "base")?;
        let base_obj = base_v.as_object().ok_or_else(|| io::Error::new(
            io::ErrorKind::InvalidData,
            "BranchConditionData.base: expected object",
        ))?;
        let tag = json_get_field(base_obj, "tag")?
            .as_u64()
            .ok_or_else(|| io::Error::new(io::ErrorKind::InvalidData,
                "BranchConditionData.base.tag: expected u8"))?;
        if tag > u8::MAX as u64 {
            return Err(io::Error::new(io::ErrorKind::InvalidData,
                format!("BranchConditionData.base.tag: {} out of u8 range", tag)));
        }
        (tag as u8).write_to(w)?;
        let variant_v = json_get_field(obj, "variant")?;
        BranchConditionDataVariant::write_from_json(tag as u8, w, variant_v)?;
        Ok(())
    }
}
