//! Auto-generated polymorphic variant decoder for BranchConditionData.
//! Generated by gen_variant_enum.py from a Mac-binary-derived manifest.
//! Total variants: 14

use crate::binary::*;
use std::io::{self, Write};

/// Common base fields shared by every BranchConditionData variant.
///
/// Note: the original recipe also pulled three trailing bytes here (byte_a,
/// byte_b, byte_c). Those bytes are actually the GameCondition wrapper
/// footer (read by sub_101021408 after the tree at slots +8/+9/+10 of the
/// _gameCondition struct), not part of BranchConditionDataBase. They've
/// been moved up to `super::game_condition::GameCondition` so every root
/// case correctly accounts for them, not just BranchConditionData.
#[derive(Debug)]
pub struct BranchConditionDataBase {
    pub tag: u8,
}

impl BranchConditionDataBase {
    pub fn read_from(data: &[u8], offset: &mut usize) -> io::Result<Self> {
        let tag = u8::read_from(data, offset)?;
        Ok(Self { tag })
    }
    pub fn write_to(&self, w: &mut dyn Write) -> io::Result<()> {
        self.tag.write_to(w)?;
        Ok(())
    }
}

#[derive(Debug)]
pub struct BranchConditionDataPayload {
    pub byte_at_8: u8,
}
impl BranchConditionDataPayload {
    pub fn read_from(data: &[u8], offset: &mut usize) -> io::Result<Self> {
        let byte_at_8 = u8::read_from(data, offset)?;
        Ok(Self { byte_at_8 })
    }
    pub fn write_to(&self, w: &mut dyn Write) -> io::Result<()> {
        self.byte_at_8.write_to(w)?;
        Ok(())
    }
}

#[derive(Debug)]
pub struct BranchConditionData_QuestPayload {
    pub questinfo_id: u32,
    pub stageinfo_id: u32,
}
impl BranchConditionData_QuestPayload {
    pub fn read_from(data: &[u8], offset: &mut usize) -> io::Result<Self> {
        let questinfo_id = u32::read_from(data, offset)?;
        let stageinfo_id = u32::read_from(data, offset)?;
        Ok(Self { questinfo_id, stageinfo_id })
    }
    pub fn write_to(&self, w: &mut dyn Write) -> io::Result<()> {
        self.questinfo_id.write_to(w)?;
        self.stageinfo_id.write_to(w)?;
        Ok(())
    }
}

#[derive(Debug)]
pub struct BranchConditionData_MissionPayload {
    pub missioninfo_id: u32,
}
impl BranchConditionData_MissionPayload {
    pub fn read_from(data: &[u8], offset: &mut usize) -> io::Result<Self> {
        let missioninfo_id = u32::read_from(data, offset)?;
        Ok(Self { missioninfo_id })
    }
    pub fn write_to(&self, w: &mut dyn Write) -> io::Result<()> {
        self.missioninfo_id.write_to(w)?;
        Ok(())
    }
}

#[derive(Debug)]
pub struct BranchConditionData_SubMissionPayload {
    pub missioninfo_id: u32,
    pub submission_idx: u32,
}
impl BranchConditionData_SubMissionPayload {
    pub fn read_from(data: &[u8], offset: &mut usize) -> io::Result<Self> {
        let missioninfo_id = u32::read_from(data, offset)?;
        let submission_idx = u32::read_from(data, offset)?;
        Ok(Self { missioninfo_id, submission_idx })
    }
    pub fn write_to(&self, w: &mut dyn Write) -> io::Result<()> {
        self.missioninfo_id.write_to(w)?;
        self.submission_idx.write_to(w)?;
        Ok(())
    }
}

#[derive(Debug)]
pub struct BranchConditionData_StagePayload {
    pub stageinfo_id: u32,
}
impl BranchConditionData_StagePayload {
    pub fn read_from(data: &[u8], offset: &mut usize) -> io::Result<Self> {
        let stageinfo_id = u32::read_from(data, offset)?;
        Ok(Self { stageinfo_id })
    }
    pub fn write_to(&self, w: &mut dyn Write) -> io::Result<()> {
        self.stageinfo_id.write_to(w)?;
        Ok(())
    }
}

#[derive(Debug)]
pub struct BranchConditionData_KnowledgePayload {
    pub knowledgeinfo_id: u32,
    pub knowledge_field: u32,
}
impl BranchConditionData_KnowledgePayload {
    pub fn read_from(data: &[u8], offset: &mut usize) -> io::Result<Self> {
        let knowledgeinfo_id = u32::read_from(data, offset)?;
        let knowledge_field = u32::read_from(data, offset)?;
        Ok(Self { knowledgeinfo_id, knowledge_field })
    }
    pub fn write_to(&self, w: &mut dyn Write) -> io::Result<()> {
        self.knowledgeinfo_id.write_to(w)?;
        self.knowledge_field.write_to(w)?;
        Ok(())
    }
}

#[derive(Debug)]
pub struct BranchConditionData_ItemPayload {
    pub iteminfo_id: u32,
    pub item_count: u64,
}
impl BranchConditionData_ItemPayload {
    pub fn read_from(data: &[u8], offset: &mut usize) -> io::Result<Self> {
        let iteminfo_id = u32::read_from(data, offset)?;
        let item_count = u64::read_from(data, offset)?;
        Ok(Self { iteminfo_id, item_count })
    }
    pub fn write_to(&self, w: &mut dyn Write) -> io::Result<()> {
        self.iteminfo_id.write_to(w)?;
        self.item_count.write_to(w)?;
        Ok(())
    }
}

#[derive(Debug)]
pub struct BranchConditionData_IsHiredMercenaryPayload {
    pub characterinfo_id: u32,
}
impl BranchConditionData_IsHiredMercenaryPayload {
    pub fn read_from(data: &[u8], offset: &mut usize) -> io::Result<Self> {
        let characterinfo_id = u32::read_from(data, offset)?;
        Ok(Self { characterinfo_id })
    }
    pub fn write_to(&self, w: &mut dyn Write) -> io::Result<()> {
        self.characterinfo_id.write_to(w)?;
        Ok(())
    }
}

#[derive(Debug)]
pub struct BranchConditionData_IsHiredMercenaryTypePayload {
    pub mercenary_type: u8,
}
impl BranchConditionData_IsHiredMercenaryTypePayload {
    pub fn read_from(data: &[u8], offset: &mut usize) -> io::Result<Self> {
        let mercenary_type = u8::read_from(data, offset)?;
        Ok(Self { mercenary_type })
    }
    pub fn write_to(&self, w: &mut dyn Write) -> io::Result<()> {
        self.mercenary_type.write_to(w)?;
        Ok(())
    }
}

#[derive(Debug)]
pub struct BranchConditionData_BranchIndexPayload {
    pub branch_index: u8,
    pub branch_flag: u8,
}
impl BranchConditionData_BranchIndexPayload {
    pub fn read_from(data: &[u8], offset: &mut usize) -> io::Result<Self> {
        let branch_index = u8::read_from(data, offset)?;
        let branch_flag = u8::read_from(data, offset)?;
        Ok(Self { branch_index, branch_flag })
    }
    pub fn write_to(&self, w: &mut dyn Write) -> io::Result<()> {
        self.branch_index.write_to(w)?;
        self.branch_flag.write_to(w)?;
        Ok(())
    }
}

#[derive(Debug)]
pub struct BranchConditionData_BranchPayload {
    pub byte_at_8: u8,
}
impl BranchConditionData_BranchPayload {
    pub fn read_from(data: &[u8], offset: &mut usize) -> io::Result<Self> {
        let byte_at_8 = u8::read_from(data, offset)?;
        Ok(Self { byte_at_8 })
    }
    pub fn write_to(&self, w: &mut dyn Write) -> io::Result<()> {
        self.byte_at_8.write_to(w)?;
        Ok(())
    }
}

#[derive(Debug)]
pub struct BranchConditionData_NearMissionPayload {
    pub byte_at_8: u8,
}
impl BranchConditionData_NearMissionPayload {
    pub fn read_from(data: &[u8], offset: &mut usize) -> io::Result<Self> {
        let byte_at_8 = u8::read_from(data, offset)?;
        Ok(Self { byte_at_8 })
    }
    pub fn write_to(&self, w: &mut dyn Write) -> io::Result<()> {
        self.byte_at_8.write_to(w)?;
        Ok(())
    }
}

#[derive(Debug)]
pub struct BranchConditionData_GameLevelStatePayload<'a> {
    pub levelinfo_id: u32,
    pub state_name: CString<'a>,
}
impl<'a> BranchConditionData_GameLevelStatePayload<'a> {
    pub fn read_from(data: &'a [u8], offset: &mut usize) -> io::Result<Self> {
        let levelinfo_id = u32::read_from(data, offset)?;
        let state_name = CString::read_from(data, offset)?;
        Ok(Self { levelinfo_id, state_name })
    }
    pub fn write_to(&self, w: &mut dyn Write) -> io::Result<()> {
        self.levelinfo_id.write_to(w)?;
        self.state_name.write_to(w)?;
        Ok(())
    }
}

#[derive(Debug)]
pub struct BranchConditionData_GamePlayVariablePayload {
    pub gameplayvariableinfo_id: u32,
    pub gpv_flag: u8,
}
impl BranchConditionData_GamePlayVariablePayload {
    pub fn read_from(data: &[u8], offset: &mut usize) -> io::Result<Self> {
        let gameplayvariableinfo_id = u32::read_from(data, offset)?;
        let gpv_flag = u8::read_from(data, offset)?;
        Ok(Self { gameplayvariableinfo_id, gpv_flag })
    }
    pub fn write_to(&self, w: &mut dyn Write) -> io::Result<()> {
        self.gameplayvariableinfo_id.write_to(w)?;
        self.gpv_flag.write_to(w)?;
        Ok(())
    }
}

/// BranchConditionData variant — discriminated union of 14 cases.
#[derive(Debug)]
pub enum BranchConditionDataVariant<'a> {
    BranchConditionData(BranchConditionDataPayload),
    BranchConditionData_Quest(BranchConditionData_QuestPayload),
    BranchConditionData_Mission(BranchConditionData_MissionPayload),
    BranchConditionData_SubMission(BranchConditionData_SubMissionPayload),
    BranchConditionData_Stage(BranchConditionData_StagePayload),
    BranchConditionData_Knowledge(BranchConditionData_KnowledgePayload),
    BranchConditionData_Item(BranchConditionData_ItemPayload),
    BranchConditionData_IsHiredMercenary(BranchConditionData_IsHiredMercenaryPayload),
    BranchConditionData_IsHiredMercenaryType(BranchConditionData_IsHiredMercenaryTypePayload),
    BranchConditionData_BranchIndex(BranchConditionData_BranchIndexPayload),
    BranchConditionData_Branch(BranchConditionData_BranchPayload),
    BranchConditionData_NearMission(BranchConditionData_NearMissionPayload),
    BranchConditionData_GameLevelState(BranchConditionData_GameLevelStatePayload<'a>),
    BranchConditionData_GamePlayVariable(BranchConditionData_GamePlayVariablePayload),
}

impl<'a> BranchConditionDataVariant<'a> {
    pub fn discriminator(&self) -> u8 {
        match self {
            Self::BranchConditionData(_) => 0,
            Self::BranchConditionData_Quest(_) => 1,
            Self::BranchConditionData_Mission(_) => 2,
            Self::BranchConditionData_SubMission(_) => 3,
            Self::BranchConditionData_Stage(_) => 4,
            Self::BranchConditionData_Knowledge(_) => 5,
            Self::BranchConditionData_Item(_) => 6,
            Self::BranchConditionData_IsHiredMercenary(_) => 7,
            Self::BranchConditionData_IsHiredMercenaryType(_) => 8,
            Self::BranchConditionData_BranchIndex(_) => 9,
            Self::BranchConditionData_Branch(_) => 10,
            Self::BranchConditionData_NearMission(_) => 11,
            Self::BranchConditionData_GameLevelState(_) => 12,
            Self::BranchConditionData_GamePlayVariable(_) => 13,
        }
    }

    pub fn read_from(disc: u8, data: &'a [u8], offset: &mut usize) -> io::Result<Self> {
        Ok(match disc {
            0 => Self::BranchConditionData(BranchConditionDataPayload::read_from(data, offset)?),
            1 => Self::BranchConditionData_Quest(BranchConditionData_QuestPayload::read_from(data, offset)?),
            2 => Self::BranchConditionData_Mission(BranchConditionData_MissionPayload::read_from(data, offset)?),
            3 => Self::BranchConditionData_SubMission(BranchConditionData_SubMissionPayload::read_from(data, offset)?),
            4 => Self::BranchConditionData_Stage(BranchConditionData_StagePayload::read_from(data, offset)?),
            5 => Self::BranchConditionData_Knowledge(BranchConditionData_KnowledgePayload::read_from(data, offset)?),
            6 => Self::BranchConditionData_Item(BranchConditionData_ItemPayload::read_from(data, offset)?),
            7 => Self::BranchConditionData_IsHiredMercenary(BranchConditionData_IsHiredMercenaryPayload::read_from(data, offset)?),
            8 => Self::BranchConditionData_IsHiredMercenaryType(BranchConditionData_IsHiredMercenaryTypePayload::read_from(data, offset)?),
            9 => Self::BranchConditionData_BranchIndex(BranchConditionData_BranchIndexPayload::read_from(data, offset)?),
            10 => Self::BranchConditionData_Branch(BranchConditionData_BranchPayload::read_from(data, offset)?),
            11 => Self::BranchConditionData_NearMission(BranchConditionData_NearMissionPayload::read_from(data, offset)?),
            12 => Self::BranchConditionData_GameLevelState(BranchConditionData_GameLevelStatePayload::read_from(data, offset)?),
            13 => Self::BranchConditionData_GamePlayVariable(BranchConditionData_GamePlayVariablePayload::read_from(data, offset)?),
            _ => return Err(io::Error::new(io::ErrorKind::InvalidData, format!("unknown BranchConditionData disc: {}", disc))),
        })
    }

    pub fn write_to(&self, w: &mut dyn Write) -> io::Result<()> {
        match self {
            Self::BranchConditionData(p) => p.write_to(w),
            Self::BranchConditionData_Quest(p) => p.write_to(w),
            Self::BranchConditionData_Mission(p) => p.write_to(w),
            Self::BranchConditionData_SubMission(p) => p.write_to(w),
            Self::BranchConditionData_Stage(p) => p.write_to(w),
            Self::BranchConditionData_Knowledge(p) => p.write_to(w),
            Self::BranchConditionData_Item(p) => p.write_to(w),
            Self::BranchConditionData_IsHiredMercenary(p) => p.write_to(w),
            Self::BranchConditionData_IsHiredMercenaryType(p) => p.write_to(w),
            Self::BranchConditionData_BranchIndex(p) => p.write_to(w),
            Self::BranchConditionData_Branch(p) => p.write_to(w),
            Self::BranchConditionData_NearMission(p) => p.write_to(w),
            Self::BranchConditionData_GameLevelState(p) => p.write_to(w),
            Self::BranchConditionData_GamePlayVariable(p) => p.write_to(w),
        }
    }
}

/// Full BranchConditionData record: 1-byte tag + base + variant payload.
#[derive(Debug)]
pub struct BranchConditionData<'a> {
    pub base: BranchConditionDataBase,
    pub variant: BranchConditionDataVariant<'a>,
}

impl<'a> BranchConditionData<'a> {
    pub fn read_from(data: &'a [u8], offset: &mut usize) -> io::Result<Self> {
        let base = BranchConditionDataBase::read_from(data, offset)?;
        let disc = base.tag;
        let variant = BranchConditionDataVariant::read_from(disc, data, offset)?;
        Ok(Self { base, variant })
    }
    pub fn write_to(&self, w: &mut dyn Write) -> io::Result<()> {
        // tag is the first byte of base — base.write_to writes it
        self.base.write_to(w)?;
        self.variant.write_to(w)?;
        Ok(())
    }
}
