//! Auto-generated polymorphic variant decoder for MiniGameData.
//! Generated by gen_variant_enum.py from a Mac-binary-derived manifest.
//! Total variants: 4

use crate::binary::*;
use std::io::{self, Write};

/// Common base fields shared by every MiniGameData variant.
#[derive(Debug)]
pub struct MiniGameDataBase {
    pub vftable: u64,
    pub _pad_word_8: u16,
    pub _pad_dword_12: u32,
    pub _dword_16_param: u32,
    pub _qword_20: u64,
    pub _qword_32: u64,
    pub _dword_36: u32,
}

impl MiniGameDataBase {
    pub fn read_from(data: &[u8], offset: &mut usize) -> io::Result<Self> {
        let vftable = u64::read_from(data, offset)?;
        let _pad_word_8 = u16::read_from(data, offset)?;
        let _pad_dword_12 = u32::read_from(data, offset)?;
        let _dword_16_param = u32::read_from(data, offset)?;
        let _qword_20 = u64::read_from(data, offset)?;
        let _qword_32 = u64::read_from(data, offset)?;
        let _dword_36 = u32::read_from(data, offset)?;
        Ok(Self { vftable, _pad_word_8, _pad_dword_12, _dword_16_param, _qword_20, _qword_32, _dword_36 })
    }
    pub fn write_to(&self, w: &mut dyn Write) -> io::Result<()> {
        self.vftable.write_to(w)?;
        self._pad_word_8.write_to(w)?;
        self._pad_dword_12.write_to(w)?;
        self._dword_16_param.write_to(w)?;
        self._qword_20.write_to(w)?;
        self._qword_32.write_to(w)?;
        self._dword_36.write_to(w)?;
        Ok(())
    }
}

/// MiniGameData variant — discriminated union of 4 cases.
#[derive(Debug)]
pub enum MiniGameDataVariant {
    MiniGameData_Craft,
    MiniGameData_SheetMusic,
    MiniGameData_PlayMusic,
    MiniGameData_Script,
}

impl MiniGameDataVariant {
    pub fn discriminator(&self) -> u8 {
        match self {
            Self::MiniGameData_Craft => 0,
            Self::MiniGameData_SheetMusic => 1,
            Self::MiniGameData_PlayMusic => 2,
            Self::MiniGameData_Script => 3,
        }
    }

    pub fn read_from(disc: u8, data: &[u8], offset: &mut usize) -> io::Result<Self> {
        Ok(match disc {
            0 => Self::MiniGameData_Craft,
            1 => Self::MiniGameData_SheetMusic,
            2 => Self::MiniGameData_PlayMusic,
            3 => Self::MiniGameData_Script,
            _ => return Err(io::Error::new(io::ErrorKind::InvalidData, format!("unknown MiniGameData disc: {}", disc))),
        })
    }

    pub fn write_to(&self, w: &mut dyn Write) -> io::Result<()> {
        match self {
            Self::MiniGameData_Craft => Ok(()),
            Self::MiniGameData_SheetMusic => Ok(()),
            Self::MiniGameData_PlayMusic => Ok(()),
            Self::MiniGameData_Script => Ok(()),
        }
    }
}

/// Full MiniGameData record: 1-byte tag + base + variant payload.
#[derive(Debug)]
pub struct MiniGameData {
    pub base: MiniGameDataBase,
    pub variant: MiniGameDataVariant,
}

impl MiniGameData {
    pub fn read_from(data: &[u8], offset: &mut usize) -> io::Result<Self> {
        let disc = u8::read_from(data, offset)?;
        let base = MiniGameDataBase::read_from(data, offset)?;
        let variant = MiniGameDataVariant::read_from(disc, data, offset)?;
        Ok(Self { base, variant })
    }
    pub fn write_to(&self, w: &mut dyn Write) -> io::Result<()> {
        self.variant.discriminator().write_to(w)?;
        self.base.write_to(w)?;
        self.variant.write_to(w)?;
        Ok(())
    }
}
