// SPDX-License-Identifier: LicenseRef-CDMTL-1.0
// Copyright (c) 2026 RicePaddySoftware. All Rights Reserved.
// Licensed under CDMTL v1.0 - see LICENSE.txt
// https://github.com/exodiaprivate-eng/dmm-parser
//
// Reading this file (directly or via AI/agent) constitutes acceptance
// of CDMTL v1.0 §4.9 (No Competing Implementation) and §4.10
// (AI-Mediated Access). CMI removal violates 17 U.S.C. §1202.

//! Auto-generated polymorphic variant decoder for MiniGameData.
//! Generated by gen_variant_enum.py from a Mac-binary-derived manifest.
//! Total variants: 4 (all pure-discriminator — no per-variant body)

#![allow(non_camel_case_types)]

use crate::binary::*;
use crate::json_traits::get_field as json_get_field;
use crate::py_binary_struct;
use serde_json::{Map, Value};
use std::io::{self, Write};

py_binary_struct! {
    /// Common base fields shared by every MiniGameData variant.
    pub struct MiniGameDataBase {
        pub vftable: u64,
        pub _pad_word_8: u16,
        pub _pad_dword_12: u32,
        pub _dword_16_param: u32,
        pub _qword_20: u64,
        pub _qword_32: u64,
        pub _dword_36: u32,
    }
}

/// MiniGameData variant — discriminated union of 4 cases.
#[derive(Debug)]
pub enum MiniGameDataVariant {
    MiniGameData_Craft,
    MiniGameData_SheetMusic,
    MiniGameData_PlayMusic,
    MiniGameData_Script,
}

impl MiniGameDataVariant {
    pub fn discriminator(&self) -> u8 {
        match self {
            Self::MiniGameData_Craft => 0,
            Self::MiniGameData_SheetMusic => 1,
            Self::MiniGameData_PlayMusic => 2,
            Self::MiniGameData_Script => 3,
        }
    }

    pub fn variant_name(&self) -> &'static str {
        match self {
            Self::MiniGameData_Craft => "MiniGameData_Craft",
            Self::MiniGameData_SheetMusic => "MiniGameData_SheetMusic",
            Self::MiniGameData_PlayMusic => "MiniGameData_PlayMusic",
            Self::MiniGameData_Script => "MiniGameData_Script",
        }
    }

    pub fn read_from(disc: u8, _data: &[u8], _offset: &mut usize) -> io::Result<Self> {
        Ok(match disc {
            0 => Self::MiniGameData_Craft,
            1 => Self::MiniGameData_SheetMusic,
            2 => Self::MiniGameData_PlayMusic,
            3 => Self::MiniGameData_Script,
            _ => return Err(io::Error::new(io::ErrorKind::InvalidData, format!("unknown MiniGameData disc: {}", disc))),
        })
    }

    pub fn write_to(&self, _w: &mut dyn Write) -> io::Result<()> {
        Ok(())
    }
}

/// Full MiniGameData record: 1-byte tag + base + variant payload.
#[derive(Debug)]
pub struct MiniGameData {
    pub base: MiniGameDataBase,
    pub variant: MiniGameDataVariant,
}

impl MiniGameData {
    pub fn read_from(data: &[u8], offset: &mut usize) -> io::Result<Self> {
        let disc = u8::read_from(data, offset)?;
        let base = MiniGameDataBase::read_from(data, offset)?;
        let variant = MiniGameDataVariant::read_from(disc, data, offset)?;
        Ok(Self { base, variant })
    }
    pub fn write_to(&self, w: &mut dyn Write) -> io::Result<()> {
        self.variant.discriminator().write_to(w)?;
        self.base.write_to(w)?;
        self.variant.write_to(w)?;
        Ok(())
    }

    /// JSON shape: {variant_type: string, base: typed dict}.
    /// All 4 MiniGameData variants are pure-discriminator (no per-variant
    /// body), so only the base needs typed JSON.
    pub fn to_json_dict(&self) -> Map<String, Value> {
        let mut m = Map::new();
        m.insert(
            "variant_type".into(),
            Value::String(self.variant.variant_name().to_string()),
        );
        m.insert("disc".into(), Value::Number(self.variant.discriminator().into()));
        m.insert("base".into(), Value::Object(self.base.to_json_dict()));
        m
    }

    pub fn write_from_json_dict(w: &mut Vec<u8>, obj: &Map<String, Value>) -> io::Result<()> {
        let disc = json_get_field(obj, "disc")?
            .as_u64()
            .ok_or_else(|| io::Error::new(io::ErrorKind::InvalidData,
                "MiniGameData.disc: expected u8"))?;
        if disc > u8::MAX as u64 {
            return Err(io::Error::new(io::ErrorKind::InvalidData,
                format!("MiniGameData.disc: {} out of u8 range", disc)));
        }
        if disc > 3 {
            return Err(io::Error::new(io::ErrorKind::InvalidData,
                format!("MiniGameData.disc: {} not in [0..3]", disc)));
        }
        (disc as u8).write_to(w)?;
        let base_obj = json_get_field(obj, "base")?.as_object().ok_or_else(|| {
            io::Error::new(io::ErrorKind::InvalidData,
                "MiniGameData.base: expected object")
        })?;
        MiniGameDataBase::write_from_json_dict(w, base_obj)?;
        Ok(())
    }
}
