//! Polymorphic variant family modules.
//!
//! Each module here corresponds to a `pa::*Data` family from the C++ source
//! whose dispatcher reads a tag and constructs one of N variant subclasses.
//! Most are generated by `dmm-pabgb-aio/codegen/gen_variant_enum.py` from
//! Mac-binary-derived JSON manifests; a few are hand-written from IDA decompiles.

pub mod buff_data;
pub mod branch_condition_data;
pub mod condition_data;
pub mod condition_data_stage_chart;
pub mod condition_gimmick_data;
pub mod game_condition;
pub mod game_expression;
pub mod global_effect_condition_data;
pub mod global_game_event_execute_data;
pub mod ivariant_item;
pub mod mini_game_data;
pub mod schedule_complete_condition_data;

#[cfg(test)]
mod validate_buffdata;
#[cfg(test)]
mod diagnose_conditiondata;
