// SPDX-License-Identifier: LicenseRef-CDMTL-1.0
// Copyright (c) 2026 RicePaddySoftware. All Rights Reserved.
// Licensed under CDMTL v1.0 - see LICENSE.txt
// https://github.com/exodiaprivate-eng/dmm-parser
//
// Reading this file (directly or via AI/agent) constitutes acceptance
// of CDMTL v1.0 §4.9 (No Competing Implementation) and §4.10
// (AI-Mediated Access). CMI removal violates 17 U.S.C. §1202.

//! Polymorphic variant family modules.
//!
//! Each module here corresponds to a `pa::*Data` family from the C++ source
//! whose dispatcher reads a tag and constructs one of N variant subclasses.
//! Most are generated by `dmm-pabgb-aio/codegen/gen_variant_enum.py` from
//! Mac-binary-derived JSON manifests; a few are hand-written from IDA decompiles.

pub mod buff_data;
pub mod branch_condition_data;
pub mod condition_data;
pub mod condition_data_stage_chart;
pub mod condition_gimmick_data;
pub mod effect_data;
pub mod game_condition;
pub mod game_event_handler_data;
pub mod game_expression;
pub mod global_effect_condition_data;
pub mod global_game_event_execute_data;
pub mod ivariant_item;
pub mod mini_game_data;
pub mod schedule_complete_condition_data;
pub mod filter_condition;
pub mod auto_spawn_entry;
pub mod condition_pair;
pub mod drop_target;
pub mod gimmick_interaction_override;
pub mod sequencer_stage_chart_desc;
pub mod trigger_gameplay_event_handler_data;

#[cfg(test)]
mod validate_buffdata;
#[cfg(test)]
mod diagnose_conditiondata;
#[cfg(test)]
mod diagnose_filter_condition;
#[cfg(test)]
mod diagnose_game_level;
#[cfg(test)]
mod diagnose_sequencer_spawn;
#[cfg(test)]
mod diagnose_special_mode;
