// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Each entry maps the Rust struct field name (snake_case, what shape='v3'
// emits today) to the canonical Pearl Abyss C++ identifier (with leading
// underscore, what shape='v3.1' emits). Mechanical transliteration:
// snake_case → prepend `_` + lowerCamelCase. v3 names are NEVER overwritten;
// these aliases just enable v3.1 consumers (DMM v2.0.0-beta etc.) to request
// the canonical names.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("craft_tool_info", "_craftToolInfo"),
    ("item_consume_type", "_itemConsumeType"),
    ("condition_list", "_conditionList"),
    ("need_knowledge_info", "_needKnowledgeInfo"),
    ("craft_tag_name", "_craftTagName"),
    ("is_from_item_info", "_isFromItemInfo"),
    ("is_result_item_for_warehouse", "_isResultItemForWarehouse"),
    ("is_with_sealed_item", "_isWithSealedItem"),
    ("is_apply_enchant_level", "_isApplyEnchantLevel"),
    ("is_material_item_only_same_item_no", "_isMaterialItemOnlySameItemNo"),
    ("is_allow_material_item_self_same", "_isAllowMaterialItemSelfSame"),
    ("fixed_material_data_list", "_fixedMaterialDataList"),
    ("recipe_item_group_info_list", "_recipeItemGroupInfoList"),
    ("elemental_status_info", "_elementalStatusInfo"),
    ("elemental_material_state_list", "_elementalMaterialStateList"),
    ("name", "_name"),
    ("description", "_description"),
    ("enchant_recipe_desc", "_enchantRecipeDesc"),
    ("group_string_info", "_groupStringInfo"),
    ("sub_group_string_info", "_subGroupStringInfo"),
    ("complete_description", "_completeDescription"),
    ("result_drop_info_list", "_resultDropInfoList"),
    ("additional_drop_info_list", "_additionalDropInfoList"),
];
