// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Schema-verified: each canonical name was matched against
// NattKh/CrimsonDesertModdingTools `pabgb_complete_schema.json`
// (canonical PA identifiers extracted from Korean error strings
// in CrimsonDesert.exe). Only fields whose mechanical snake→camel
// translation matched a known canonical name were shipped.
//
// v3 (snake_case) is the default emit; v3.1 emits the canonical `_camelCase`
// form. Round-trips identically — both names accepted on input.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("craft_tool_info", "_craftToolInfo"),
    ("item_consume_type", "_itemConsumeType"),
    ("condition_list", "_conditionList"),
    ("need_knowledge_info", "_needKnowledgeInfo"),
    ("is_from_item_info", "_isFromItemInfo"),
    ("is_result_item_for_warehouse", "_isResultItemForWarehouse"),
    ("is_with_sealed_item", "_isWithSealedItem"),
    ("is_apply_enchant_level", "_isApplyEnchantLevel"),
    ("is_material_item_only_same_item_no", "_isMaterialItemOnlySameItemNo"),
    ("is_allow_material_item_self_same", "_isAllowMaterialItemSelfSame"),
    ("fixed_material_data_list", "_fixedMaterialDataList"),
    ("recipe_item_group_info_list", "_recipeItemGroupInfoList"),
    ("elemental_status_info", "_elementalStatusInfo"),
    ("elemental_material_state_list", "_elementalMaterialStateList"),
    ("name", "_name"),
    ("description", "_description"),
    ("enchant_recipe_desc", "_enchantRecipeDesc"),
    ("group_string_info", "_groupStringInfo"),
    ("sub_group_string_info", "_subGroupStringInfo"),
    ("result_drop_info_list", "_resultDropInfoList"),
    ("additional_drop_info_list", "_additionalDropInfoList"),
];
