// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Schema-verified: each canonical name was matched against
// NattKh/CrimsonDesertModdingTools `pabgb_complete_schema.json`
// (canonical PA identifiers extracted from Korean error strings
// in CrimsonDesert.exe). Only fields whose mechanical snake→camel
// translation matched a known canonical name were shipped.
//
// v3 (snake_case) is the default emit; v3.1 emits the canonical `_camelCase`
// form. Round-trips identically — both names accepted on input.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("start_ai_event_hash", "_startAiEventHash"),
    ("end_ai_event_hash", "_endAiEventHash"),
    ("order", "_order"),
    ("action_restriction_type", "_actionRestrictionType"),
    ("regist_type_status", "_registTypeStatus"),
    ("skill_info", "_skillInfo"),
    ("spawn_action_list", "_spawnActionList"),
    ("ai_event_tag_name_hash", "_aiEventTagNameHash"),
    ("ignore_catch", "_ignoreCatch"),
    ("ignore_throw", "_ignoreThrow"),
    ("delay_dead_fatal", "_delayDeadFatal"),
    ("delay_knock_out", "_delayKnockOut"),
    ("use_random_hit_dir", "_useRandomHitDir"),
    ("use_auto_attack_throw", "_useAutoAttackThrow"),
    ("additive_skill", "_additiveSkill"),
];
