// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Schema-verified: each canonical name was matched against
// NattKh/CrimsonDesertModdingTools `pabgb_complete_schema.json`
// (canonical PA identifiers extracted from Korean error strings
// in CrimsonDesert.exe). Only fields whose mechanical snake→camel
// translation matched a known canonical name were shipped.
//
// v3 (snake_case) is the default emit; v3.1 emits the canonical `_camelCase`
// form. Round-trips identically — both names accepted on input.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("possible_list", "_possibleList"),
    ("auto_spawn_spline_name", "_autoSpawnSplineName"),
    ("auto_spawn_spline_except_name", "_autoSpawnSplineExceptName"),
    ("region_info_list", "_regionInfoList"),
    ("not_spawn_region_info_list", "_notSpawnRegionInfoList"),
    ("spawn_region_tag_list", "_spawnRegionTagList"),
    ("not_spawn_region_tag_list", "_notSpawnRegionTagList"),
    ("spawn_list", "_spawnList"),
    ("voxel_type", "_voxelType"),
    ("road_group_type", "_roadGroupType"),
    ("is_only_summon_data", "_isOnlySummonData"),
    ("is_only_check_data", "_isOnlyCheckData"),
    ("stage_category", "_stageCategory"),
    ("tag_list", "_tagList"),
    ("is_default_activated", "_isDefaultActivated"),
    ("all_terrain_region", "_allTerrainRegion"),
    ("bitmap_position_info", "_bitmapPositionInfo"),
    ("bitmap_color_list_for_spawn", "_bitmapColorListForSpawn"),
    ("spawn_at_height_field_landscape", "_spawnAtHeightFieldLandScape"),
    ("fish_summon_time_frequency_type", "_fishSummonTimeFrquencyType"),
    ("spawn_reason_list", "_spawnReasonList"),
];
