// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Each entry maps the Rust struct field name (snake_case, what shape='v3'
// emits today) to the canonical Pearl Abyss C++ identifier (with leading
// underscore, what shape='v3.1' emits). Mechanical transliteration:
// snake_case → prepend `_` + lowerCamelCase. v3 names are NEVER overwritten;
// these aliases just enable v3.1 consumers (DMM v2.0.0-beta etc.) to request
// the canonical names.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("min_level", "_minLevel"),
    ("max_level", "_maxLevel"),
    ("exp_a", "_expA"),
    ("exp_b", "_expB"),
    ("exp_c", "_expC"),
    ("exp_d", "_expD"),
    ("condition_info", "_conditionInfo"),
    ("alert_component_name", "_alertComponentName"),
    ("alert_component_name_for_vary_exp", "_alertComponentNameForVaryExp"),
    ("knowledge_info", "_knowledgeInfo"),
    ("buff_info", "_buffInfo"),
    ("money_info", "_moneyInfo"),
    ("reward_drop_set_info", "_rewardDropSetInfo"),
    ("sub_level_exp_data_list", "_subLevelExpDataList"),
    ("additional_reward_list", "_additionalRewardList"),
    ("vary_experience_list", "_varyExperienceList"),
    ("vary_exp_per_donation_data_list", "_varyExpPerDonationDataList"),
    ("additional_buff_apply_mercenary_info", "_additionalBuffApplyMercenaryInfo"),
    ("faction_info_for_contribution", "_factionInfoForContribution"),
    ("global_stage_sequencer_info", "_globalStageSequencerInfo"),
    ("buff_add_percent_type", "_buffAddPercentType"),
    ("exp_icon_path", "_expIconPath"),
    ("is_relative_with_camp", "_isRelativeWithCamp"),
];
