// Auto-generated by scripts/generate_v3_1_aliases.py — do NOT hand-edit.
// To regenerate, re-run the script after any table struct field changes.
//
// Schema-verified: each canonical name was matched against
// NattKh/CrimsonDesertModdingTools `pabgb_complete_schema.json`
// (canonical PA identifiers extracted from Korean error strings
// in CrimsonDesert.exe). Only fields whose mechanical snake→camel
// translation matched a known canonical name were shipped.
//
// v3 (snake_case) is the default emit; v3.1 emits the canonical `_camelCase`
// form. Round-trips identically — both names accepted on input.

pub const FIELD_ALIASES_V3_1: &[(&str, &str)] = &[
    ("key", "_key"),
    ("string_key", "_stringKey"),
    ("is_blocked", "_isBlocked"),
    ("min_level", "_minLevel"),
    ("max_level", "_maxLevel"),
    ("condition_info", "_conditionInfo"),
    ("alert_component_name", "_alertComponentName"),
    ("alert_component_name_for_vary_exp", "_alertComponentNameForVaryExp"),
    ("knowledge_info", "_knowledgeInfo"),
    ("buff_info", "_buffInfo"),
    ("money_info", "_moneyInfo"),
    ("reward_drop_set_info", "_rewardDropSetInfo"),
    ("sub_level_exp_data_list", "_subLevelExpDataList"),
    ("additional_reward_list", "_additionalRewardList"),
    ("vary_experience_list", "_varyExperienceList"),
    ("vary_exp_per_donation_data_list", "_varyExpPerDonationDataList"),
    ("additional_buff_apply_mercenary_info", "_additionalBuffApplyMercenaryInfo"),
    ("faction_info_for_contribution", "_factionInfoForContribution"),
    ("global_stage_sequencer_info", "_globalStageSequencerInfo"),
    ("buff_add_percent_type", "_buffAddPercentType"),
    ("exp_icon_path", "_expIconPath"),
    ("is_relative_with_camp", "_isRelativeWithCamp"),
];
